using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using HeroParser.SeparatedValues.Core;

namespace HeroParser.AI;

/// <summary>
/// Provides high-performance utility methods for repairing and parsing loose, streaming, or malformed structured outputs generated by LLMs.
/// </summary>
public static class LlmRepair
{
    /// <summary>
    /// Strips markdown code block wrappers (e.g., ```csv) and repairs unclosed quotes on truncated final lines due to token cutoff.
    /// </summary>
    /// <param name="text">The raw LLM output text.</param>
    /// <param name="quote">The quote character used in the CSV schema.</param>
    /// <param name="escape">The escape character, if any, used in the CSV schema.</param>
    /// <returns>A cleaned and repaired CSV string.</returns>
    public static string RepairText(string text, char quote = '"', char? escape = '\\')
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return string.Empty;
        }

        // 0. Sanitize unpaired UTF-16 surrogates to prevent tokenizer/parser crashes
        text = SanitizeSurrogates(text);

        // 1. Strip Markdown Block Wrappers (e.g., ```csv ... ```) and conversational text
        var trimmed = text.Trim();
        int blockStart = trimmed.IndexOf("```");
        if (blockStart != -1)
        {
            int index = trimmed.IndexOf('\n', blockStart);
            if (index != -1)
            {
                int blockEnd = trimmed.IndexOf("```", index);
                trimmed = blockEnd != -1
                    ? trimmed[index..blockEnd].Trim()
                    : trimmed[index..].Trim();
            }
        }

        // Trim trailing escapes on cutoff streams to prevent escaping the closing quote we append
        if (escape.HasValue)
        {
            int escapeCount = 0;
            while (trimmed.Length - 1 - escapeCount >= 0 && trimmed[trimmed.Length - 1 - escapeCount] == escape.Value)
            {
                escapeCount++;
            }
            if (escapeCount % 2 != 0)
            {
                trimmed = trimmed[..^1];
            }
        }

        // 2. Scan and repair unbalanced quotes (cutoff stream)
        bool inQuotes = false;
        bool isEscaped = false;
        for (int i = 0; i < trimmed.Length; i++)
        {
            char c = trimmed[i];
            if (escape.HasValue && c == escape.Value && !isEscaped)
            {
                isEscaped = true;
                continue;
            }

            if (c == quote && !isEscaped)
            {
                inQuotes = !inQuotes;
            }
            isEscaped = false;
        }

        if (inQuotes)
        {
            trimmed = trimmed + quote + "\n";
        }

        return trimmed;
    }

    /// <summary>
    /// Replaces unpaired high or low UTF-16 surrogates in a string with the Unicode replacement character (\uFFFD) to prevent tokenizer or JSON serialization crashes.
    /// </summary>
    public static string SanitizeSurrogates(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        char[]? rented = null;
        try
        {
            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                if (char.IsSurrogate(c))
                {
                    bool isUnpaired = false;
                    if (char.IsHighSurrogate(c))
                    {
                        if (i + 1 < text.Length && char.IsLowSurrogate(text[i + 1]))
                        {
                            i++; // Skip low surrogate as it forms a valid pair
                        }
                        else
                        {
                            isUnpaired = true;
                        }
                    }
                    else // Must be low surrogate (since isSurrogate is true)
                    {
                        isUnpaired = true;
                    }

                    if (isUnpaired)
                    {
                        if (rented == null)
                        {
                            rented = System.Buffers.ArrayPool<char>.Shared.Rent(text.Length);
                            text.CopyTo(0, rented, 0, text.Length);
                        }
                        rented[i] = '\uFFFD';
                    }
                }
            }

            return rented != null ? new string(rented, 0, text.Length) : text;
        }
        finally
        {
            if (rented != null)
            {
                System.Buffers.ArrayPool<char>.Shared.Return(rented);
            }
        }
    }

    /// <summary>
    /// Asynchronously parses and binds a string containing raw LLM output into strongly-typed records, repairing any formatting anomalies or truncation.
    /// </summary>
    /// <typeparam name="T">The record type decorated with <see cref="TabularMapAttribute"/> or <see cref="GenerateBinderAttribute"/>.</typeparam>
    /// <param name="text">The raw LLM text input.</param>
    /// <param name="options">Optional CSV parser options.</param>
    /// <returns>An async enumerable of records.</returns>
    public static async IAsyncEnumerable<T> ReadFromTextAsync<T>(string text, CsvReadOptions? options = null) where T : new()
    {
        var quote = options?.Quote ?? '"';
        var escape = options?.EscapeCharacter;
        var repaired = RepairText(text, quote, escape);

        var builder = Csv.Read<T>();
        if (options != null)
        {
            builder.WithDelimiter(options.Delimiter)
                   .WithQuote(options.Quote);
            if (options.EscapeCharacter.HasValue)
            {
                builder.WithEscapeCharacter(options.EscapeCharacter.Value);
            }
            if (options.MaxColumnCount != 100)
            {
                builder.WithMaxColumns(options.MaxColumnCount);
            }
            if (options.MaxRowCount != 100_000)
            {
                builder.WithMaxRows(options.MaxRowCount);
            }
            if (!options.UseSimdIfAvailable)
            {
                builder.DisableSimd();
            }
            if (options.AllowNewlinesInsideQuotes)
            {
                builder.AllowNewlinesInQuotes();
            }
            if (!options.EnableQuotedFields)
            {
                builder.DisableQuotedFields();
            }
            if (options.CommentCharacter.HasValue)
            {
                builder.WithCommentCharacter(options.CommentCharacter.Value);
            }
            if (options.TrimFields)
            {
                builder.TrimFields();
            }
            if (options.MaxFieldSize.HasValue)
            {
                builder.WithMaxFieldSize(options.MaxFieldSize.Value);
            }
            if (options.MaxRowSize.HasValue)
            {
                builder.WithMaxRowSize(options.MaxRowSize.Value);
            }
            if (options.MaxInputSize.HasValue)
            {
                builder.WithMaxInputSize(options.MaxInputSize.Value);
            }
        }

        var list = new List<T>();
        using (var reader = builder.FromText(repaired))
        {
            foreach (var record in reader)
            {
                list.Add(record);
            }
        }

        foreach (var record in list)
        {
            await Task.Yield();
            yield return record;
        }
    }

    /// <summary>
    /// Asynchronously streams and binds a raw LLM output stream into strongly-typed records, repairing any formatting anomalies or truncation.
    /// </summary>
    /// <typeparam name="T">The record type decorated with <see cref="TabularMapAttribute"/> or <see cref="GenerateBinderAttribute"/>.</typeparam>
    /// <param name="stream">The raw LLM output stream.</param>
    /// <param name="options">Optional CSV parser options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>An async enumerable of records.</returns>
    public static async IAsyncEnumerable<T> ReadFromStreamAsync<T>(
        Stream stream,
        CsvReadOptions? options = null,
        [EnumeratorCancellation] CancellationToken cancellationToken = default) where T : new()
    {
        ArgumentNullException.ThrowIfNull(stream);
        using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true, bufferSize: -1, leaveOpen: true);
        var text = await reader.ReadToEndAsync(cancellationToken).ConfigureAwait(false);
        var enumerable = ReadFromTextAsync<T>(text, options);
        await foreach (var record in enumerable.WithCancellation(cancellationToken).ConfigureAwait(false))
        {
            yield return record;
        }
    }
}
