using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using HeroParser.SeparatedValues.Core;

namespace HeroParser.AI;

/// <summary>
/// Provides high-performance utility methods for repairing and parsing loose, streaming, or malformed structured outputs generated by LLMs.
/// </summary>
public static class LlmRepair
{
    /// <summary>
    /// Strips markdown code block wrappers (e.g., ```csv) and repairs unclosed quotes on truncated final lines due to token cutoff.
    /// </summary>
    /// <param name="text">The raw LLM output text.</param>
    /// <param name="quote">The quote character used in the CSV schema.</param>
    /// <param name="escape">The escape character, if any, used in the CSV schema.</param>
    /// <returns>A cleaned and repaired CSV string.</returns>
    public static string RepairText(string text, char quote = '"', char? escape = '\\')
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return string.Empty;
        }

        // 1. Strip Markdown Block Wrappers (e.g., ```csv ... ```)
        var trimmed = text.Trim();
        if (trimmed.StartsWith("```"))
        {
            int index = trimmed.IndexOf('\n');
            if (index != -1)
            {
                trimmed = trimmed[(index + 1)..];
            }
            if (trimmed.EndsWith("```"))
            {
                trimmed = trimmed[..^3];
            }
            trimmed = trimmed.TrimEnd();
        }

        // 2. Scan and repair unbalanced quotes (cutoff stream)
        bool inQuotes = false;
        bool isEscaped = false;
        for (int i = 0; i < trimmed.Length; i++)
        {
            char c = trimmed[i];
            if (escape.HasValue && c == escape.Value && !isEscaped)
            {
                isEscaped = true;
                continue;
            }

            if (c == quote && !isEscaped)
            {
                inQuotes = !inQuotes;
            }
            isEscaped = false;
        }

        if (inQuotes)
        {
            trimmed = trimmed + quote + "\n";
        }

        return trimmed;
    }

    /// <summary>
    /// Asynchronously parses and binds a string containing raw LLM output into strongly-typed records, repairing any formatting anomalies or truncation.
    /// </summary>
    /// <typeparam name="T">The record type decorated with <see cref="TabularMapAttribute"/> or <see cref="GenerateBinderAttribute"/>.</typeparam>
    /// <param name="text">The raw LLM text input.</param>
    /// <param name="options">Optional CSV parser options.</param>
    /// <returns>An async enumerable of records.</returns>
    public static async IAsyncEnumerable<T> ReadFromTextAsync<T>(string text, CsvReadOptions? options = null) where T : new()
    {
        var quote = options?.Quote ?? '"';
        var escape = options?.EscapeCharacter;
        var repaired = RepairText(text, quote, escape);

        var builder = Csv.Read<T>();
        if (options != null)
        {
            builder.WithDelimiter(options.Delimiter)
                   .WithQuote(options.Quote);
            if (options.EscapeCharacter.HasValue)
            {
                builder.WithEscapeCharacter(options.EscapeCharacter.Value);
            }
            if (options.MaxColumnCount != 100)
            {
                builder.WithMaxColumns(options.MaxColumnCount);
            }
            if (options.MaxRowCount != 100_000)
            {
                builder.WithMaxRows(options.MaxRowCount);
            }
            if (!options.UseSimdIfAvailable)
            {
                builder.DisableSimd();
            }
            if (options.AllowNewlinesInsideQuotes)
            {
                builder.AllowNewlinesInQuotes();
            }
            if (!options.EnableQuotedFields)
            {
                builder.DisableQuotedFields();
            }
            if (options.CommentCharacter.HasValue)
            {
                builder.WithCommentCharacter(options.CommentCharacter.Value);
            }
            if (options.TrimFields)
            {
                builder.TrimFields();
            }
            if (options.MaxFieldSize.HasValue)
            {
                builder.WithMaxFieldSize(options.MaxFieldSize.Value);
            }
            if (options.MaxRowSize.HasValue)
            {
                builder.WithMaxRowSize(options.MaxRowSize.Value);
            }
            if (options.MaxInputSize.HasValue)
            {
                builder.WithMaxInputSize(options.MaxInputSize.Value);
            }
        }

        var list = new List<T>();
        using (var reader = builder.FromText(repaired))
        {
            foreach (var record in reader)
            {
                list.Add(record);
            }
        }

        foreach (var record in list)
        {
            await Task.Yield();
            yield return record;
        }
    }

    /// <summary>
    /// Asynchronously streams and binds a raw LLM output stream into strongly-typed records, repairing any formatting anomalies or truncation.
    /// </summary>
    /// <typeparam name="T">The record type decorated with <see cref="TabularMapAttribute"/> or <see cref="GenerateBinderAttribute"/>.</typeparam>
    /// <param name="stream">The raw LLM output stream.</param>
    /// <param name="options">Optional CSV parser options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>An async enumerable of records.</returns>
    public static async IAsyncEnumerable<T> ReadFromStreamAsync<T>(
        Stream stream,
        CsvReadOptions? options = null,
        [EnumeratorCancellation] CancellationToken cancellationToken = default) where T : new()
    {
        ArgumentNullException.ThrowIfNull(stream);
        using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true, bufferSize: -1, leaveOpen: true);
        var text = await reader.ReadToEndAsync(cancellationToken).ConfigureAwait(false);
        var enumerable = ReadFromTextAsync<T>(text, options);
        await foreach (var record in enumerable.WithCancellation(cancellationToken).ConfigureAwait(false))
        {
            yield return record;
        }
    }
}
