using System.IO.Pipelines;
using System.Text;
using HeroParser.FixedWidths;
using Xunit;

namespace HeroParser.Tests.FixedWidths;

/// <summary>
/// Round-trip a record with every supported type through the FixedWidth byte path
/// (PipeReader-based DeserializeRecordsAsync) so the source-generated byte binder
/// invokes every TryParse* method on FixedWidthUtf8BindingHelper. Targets coverage
/// gaps in FixedWidthRecordBinder and FixedWidthUtf8BindingHelper.
/// </summary>
[Trait("Category", "Unit")]
public class FixedWidthAllTypesByteRoundTripTests
{
    public enum Color { Red, Green, Blue }

    [GenerateBinder]
    public sealed class AllTypes
    {
        [PositionalMap(Start = 0, Length = 10)]
        public string Text { get; set; } = "";

        [PositionalMap(Start = 10, Length = 5, Alignment = FieldAlignment.Right, PadChar = '0')]
        public int IntValue { get; set; }

        [PositionalMap(Start = 15, Length = 10, Alignment = FieldAlignment.Right, PadChar = '0')]
        public long LongValue { get; set; }

        [PositionalMap(Start = 25, Length = 5, Alignment = FieldAlignment.Right, PadChar = '0')]
        public short ShortValue { get; set; }

        [PositionalMap(Start = 30, Length = 3, Alignment = FieldAlignment.Right, PadChar = '0')]
        public byte ByteValue { get; set; }

        [PositionalMap(Start = 33, Length = 8)]
        public decimal DecimalValue { get; set; }

        [PositionalMap(Start = 41, Length = 8)]
        public double DoubleValue { get; set; }

        [PositionalMap(Start = 49, Length = 8)]
        public float FloatValue { get; set; }

        [PositionalMap(Start = 57, Length = 5)]
        public bool BoolValue { get; set; }

        [PositionalMap(Start = 62, Length = 8)]
        [Parse(Format = "yyyyMMdd")]
        public DateTime DateTimeValue { get; set; }

        [PositionalMap(Start = 70, Length = 8)]
        [Parse(Format = "yyyyMMdd")]
        public DateOnly DateOnlyValue { get; set; }

        [PositionalMap(Start = 78, Length = 4)]
        [Parse(Format = "HHmm")]
        public TimeOnly TimeOnlyValue { get; set; }

        [PositionalMap(Start = 82, Length = 36)]
        public Guid GuidValue { get; set; }

        [PositionalMap(Start = 118, Length = 5)]
        public Color EnumValue { get; set; }
    }

    [GenerateBinder]
    public sealed class NullableAll
    {
        [PositionalMap(Start = 0, Length = 5, Alignment = FieldAlignment.Right, PadChar = '0')]
        public int? IntValue { get; set; }

        [PositionalMap(Start = 5, Length = 8)]
        public decimal? DecimalValue { get; set; }

        [PositionalMap(Start = 13, Length = 5)]
        public bool? BoolValue { get; set; }

        [PositionalMap(Start = 18, Length = 8)]
        [Parse(Format = "yyyyMMdd")]
        public DateTime? DateTimeValue { get; set; }
    }

    private static byte[] EncodeRow(string row) => Encoding.UTF8.GetBytes(row + "\n");

    [Fact]
    public async Task ByteBinder_AllTypes_RoundTrip()
    {
        var line =
            "hello     " +              // Text:        10 chars
            "00042" +                    // IntValue:    "00042"
            "0000000007" +               // LongValue:   "0000000007"
            "00010" +                    // ShortValue:  "00010"
            "005" +                      // ByteValue:   "005"
            "12345.67" +                 // DecimalValue: 8 chars
            "3.141593" +                 // DoubleValue:  8 chars
            "1.250000" +                 // FloatValue:   8 chars
            "true " +                    // BoolValue:    5 chars (padded right)
            "20240115" +                 // DateTimeValue
            "20240630" +                 // DateOnlyValue
            "1030" +                     // TimeOnlyValue
            "12345678-1234-1234-1234-123456789012" + // GuidValue
            "Green";                     // EnumValue:    5 chars

        var bytes = EncodeRow(line);
        var pipe = PipeReader.Create(new MemoryStream(bytes));

        var records = new List<AllTypes>();
        await foreach (var r in HeroParser.FixedWidth.DeserializeRecordsAsync<AllTypes>(
            pipe, cancellationToken: TestContext.Current.CancellationToken))
        {
            records.Add(r);
        }

        Assert.Single(records);
        var rec = records[0];
        Assert.Equal("hello", rec.Text);
        Assert.Equal(42, rec.IntValue);
        Assert.Equal(7L, rec.LongValue);
        Assert.Equal(10, rec.ShortValue);
        Assert.Equal((byte)5, rec.ByteValue);
        Assert.Equal(12345.67m, rec.DecimalValue);
        Assert.Equal(3.141593, rec.DoubleValue, 5);
        Assert.Equal(1.25f, rec.FloatValue, 4);
        Assert.True(rec.BoolValue);
        Assert.Equal(new DateTime(2024, 1, 15), rec.DateTimeValue);
        Assert.Equal(new DateOnly(2024, 6, 30), rec.DateOnlyValue);
        Assert.Equal(new TimeOnly(10, 30), rec.TimeOnlyValue);
        Assert.NotEqual(Guid.Empty, rec.GuidValue);
        Assert.Equal(Color.Green, rec.EnumValue);
    }

    [Fact]
    public async Task ByteBinder_NullableTypes_AllPresent()
    {
        var line = "00042" + "0000.001" + "true " + "20240115";
        var bytes = EncodeRow(line);
        var pipe = PipeReader.Create(new MemoryStream(bytes));

        var records = new List<NullableAll>();
        await foreach (var r in HeroParser.FixedWidth.DeserializeRecordsAsync<NullableAll>(
            pipe, cancellationToken: TestContext.Current.CancellationToken))
        {
            records.Add(r);
        }

        Assert.Single(records);
        Assert.Equal(42, records[0].IntValue);
        Assert.Equal(0.001m, records[0].DecimalValue);
        Assert.True(records[0].BoolValue);
        Assert.Equal(new DateTime(2024, 1, 15), records[0].DateTimeValue);
    }

    [Fact]
    public async Task ByteBinder_NullableTypes_BlankFieldsBecomeNull()
    {
        // All-blank fields should map to null for nullable types.
        var line = "     " + "        " + "     " + "        ";
        var bytes = EncodeRow(line);
        var pipe = PipeReader.Create(new MemoryStream(bytes));

        var records = new List<NullableAll>();
        await foreach (var r in HeroParser.FixedWidth.DeserializeRecordsAsync<NullableAll>(
            pipe, cancellationToken: TestContext.Current.CancellationToken))
        {
            records.Add(r);
        }

        Assert.Single(records);
        Assert.Null(records[0].IntValue);
        Assert.Null(records[0].DecimalValue);
        Assert.Null(records[0].BoolValue);
        Assert.Null(records[0].DateTimeValue);
    }

    [Fact]
    public async Task ByteBinder_MultipleRows()
    {
        var sb = new StringBuilder();
        for (int i = 1; i <= 5; i++)
        {
            sb.Append(i.ToString("D5"));
            sb.Append("0000.001");
            sb.Append("true ");
            sb.Append("20240115");
            sb.Append('\n');
        }
        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        var pipe = PipeReader.Create(new MemoryStream(bytes));

        var records = new List<NullableAll>();
        await foreach (var r in HeroParser.FixedWidth.DeserializeRecordsAsync<NullableAll>(
            pipe, cancellationToken: TestContext.Current.CancellationToken))
        {
            records.Add(r);
        }

        Assert.Equal(5, records.Count);
        Assert.Equal(1, records[0].IntValue);
        Assert.Equal(5, records[^1].IntValue);
    }
}
