using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using static HeroParser.Generators.GeneratorHelpers;

namespace HeroParser.Generators;

/// <summary>
/// Source generator for CSV record binders.
/// Generates inline binder classes for maximum performance binding.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CsvRecordBinderGenerator : IIncrementalGenerator
{
    private const string GENERATED_NAMESPACE = "HeroParser.SeparatedValues.Reading.Records.Binding";
    private const string BINDER_FACTORY_TYPE = "global::HeroParser.SeparatedValues.Reading.Records.Binding.CsvRecordBinderFactory";
    private const string BINDER_INTERFACE_TYPE = "global::HeroParser.SeparatedValues.Reading.Records.Binding.ICsvBinder";
    private const string ROW_TYPE = "global::HeroParser.SeparatedValues.Reading.Span.CsvCharSpanRow";
    private const string OPTIONS_TYPE = "global::HeroParser.SeparatedValues.Reading.Records.CsvRecordOptions";
    private const string EXCEPTION_TYPE = "global::HeroParser.SeparatedValues.Core.CsvException";
    private const string ERROR_CODE_TYPE = "global::HeroParser.SeparatedValues.Core.CsvErrorCode";
    private const string WRITER_TYPE = "global::HeroParser.SeparatedValues.Writing.CsvRecordWriter";
    private const string WRITER_FACTORY_TYPE = "global::HeroParser.SeparatedValues.Writing.CsvRecordWriterFactory";

    private static readonly string[] generateAttributeNames =
    [
        "HeroParser.SeparatedValues.Reading.Records.Binding.CsvGenerateBinderAttribute",
        "HeroParser.CsvGenerateBinderAttribute"
    ];

    private static readonly string[] columnAttributeNames =
    [
        "HeroParser.SeparatedValues.Reading.Records.Binding.CsvColumnAttribute",
        "HeroParser.CsvColumnAttribute"
    ];

#pragma warning disable RS2008 // Enable analyzer release tracking - not needed for internal generator
    private static readonly DiagnosticDescriptor unsupportedPropertyTypeDiagnostic = new(
        "HERO001",
        "Unsupported property type",
        "Property '{0}' of type '{1}' is not supported by the CSV record binder generator. Supported types include primitives, DateTime, DateTimeOffset, DateOnly, TimeOnly, Guid, TimeZoneInfo, and enums.",
        "HeroParser.Generators",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);
#pragma warning restore RS2008

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Use ForAttributeWithMetadataName for better caching - register for both attribute names
        var provider1 = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                generateAttributeNames[0],
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, ct) => TransformToDescriptor(ctx, ct))
            .Where(static x => x is not null);

        var provider2 = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                generateAttributeNames[1],
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, ct) => TransformToDescriptor(ctx, ct))
            .Where(static x => x is not null);

        // Combine both providers
        var combined = provider1.Collect().Combine(provider2.Collect());

        // Generate per-type typed binder files for better incrementality
        context.RegisterSourceOutput(provider1, static (spc, descriptor) => EmitTypedBinder(spc, descriptor!));
        context.RegisterSourceOutput(provider2, static (spc, descriptor) => EmitTypedBinder(spc, descriptor!));

        // Generate registration file
        context.RegisterSourceOutput(combined, static (spc, tuple) =>
        {
            var all = tuple.Left.Concat(tuple.Right).Where(x => x is not null).ToList();
            if (all.Count > 0)
                EmitRegistration(spc, all!);
        });
    }

    private static TypeDescriptor? TransformToDescriptor(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract || !IsTypeAccessible(symbol))
            return null;

        return BuildDescriptor(symbol, ct);
    }

    private static void EmitTypedBinder(SourceProductionContext context, TypeDescriptor descriptor)
    {
        // Report diagnostics
        foreach (var diag in descriptor.Diagnostics)
        {
            context.ReportDiagnostic(diag);
        }

        var binderMembers = GetMembersWithSetters(descriptor.Members);
        if (binderMembers.Count == 0)
            return;

        var builder = new SourceBuilder(16384);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GENERATED_NAMESPACE};");
        builder.AppendLine();

        // Emit inline binder class for maximum performance
        EmitInlineBinderClass(builder, descriptor.FullyQualifiedName, descriptor.SafeClassName, binderMembers);

        context.AddSource($"CsvInlineBinder.{descriptor.SafeClassName}.g.cs", builder.ToString());
    }

    private static void EmitInlineBinderClass(SourceBuilder builder, string fullyQualifiedName, string safeClassName, IReadOnlyList<MemberDescriptor> members)
    {
        var binderClassName = $"CsvInlineBinder_{safeClassName}";
        var allHaveExplicitIndex = members.All(m => m.AttributeIndex.HasValue);

        builder.AppendLine($"internal sealed class {binderClassName} : {BINDER_INTERFACE_TYPE}<{fullyQualifiedName}>");
        builder.AppendLine("{");
        builder.Indent();

        // Emit fields
        builder.AppendLine("private readonly CultureInfo _culture;");
        builder.AppendLine("private readonly bool _caseSensitiveHeaders;");
        builder.AppendLine("private readonly bool _allowMissingColumns;");
        builder.AppendLine("private readonly HashSet<string>? _nullValues;");
        builder.AppendLine();

        // Emit column index fields
        foreach (var member in members)
        {
            var defaultIndex = member.AttributeIndex?.ToString() ?? "-1";
            builder.AppendLine($"private int _{member.MemberName}Index = {defaultIndex};");
        }
        builder.AppendLine($"private bool _resolved = {(allHaveExplicitIndex ? "true" : "false")};");
        builder.AppendLine();

        // Emit constructor
        builder.AppendLine($"public {binderClassName}({OPTIONS_TYPE}? options)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("_culture = options?.Culture ?? CultureInfo.InvariantCulture;");
        builder.AppendLine("_caseSensitiveHeaders = options?.CaseSensitiveHeaders ?? false;");
        builder.AppendLine("_allowMissingColumns = options?.AllowMissingColumns ?? false;");
        builder.AppendLine("_nullValues = options?.NullValues is { Count: > 0 }");
        builder.AppendLine("    ? new HashSet<string>(options.NullValues, StringComparer.Ordinal)");
        builder.AppendLine("    : null;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // Emit NeedsHeaderResolution property
        builder.AppendLine("public bool NeedsHeaderResolution => !_resolved;");
        builder.AppendLine();

        // Emit BindHeader method
        EmitBindHeaderMethod(builder, members);

        // Emit Bind method
        EmitBindMethod(builder, fullyQualifiedName);

        // Emit BindInto method (the hot path with inline code)
        EmitBindIntoMethod(builder, fullyQualifiedName, members);

        // Emit helper methods
        EmitFindHeaderIndexMethod(builder);
        EmitIsNullValueMethod(builder);
        EmitCreateParseExceptionMethod(builder);

        // Emit factory method for registration
        builder.AppendLine($"public static {BINDER_INTERFACE_TYPE}<{fullyQualifiedName}> Create({OPTIONS_TYPE}? options)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"return new {binderClassName}(options);");
        builder.Unindent();
        builder.AppendLine("}");

        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitBindHeaderMethod(SourceBuilder builder, IReadOnlyList<MemberDescriptor> members)
    {
        builder.AppendLine($"public void BindHeader({ROW_TYPE} headerRow, int rowNumber)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("if (_resolved) return;");
        builder.AppendLine();
        builder.AppendLine("var comparer = _caseSensitiveHeaders ? StringComparer.Ordinal : StringComparer.OrdinalIgnoreCase;");
        builder.AppendLine();

        foreach (var member in members)
        {
            builder.AppendLine($"_{member.MemberName}Index = FindHeaderIndex(headerRow, \"{member.HeaderName}\", comparer);");
        }
        builder.AppendLine();

        // Validate required columns
        foreach (var member in members)
        {
            var isRequired = !member.IsNullable && member.BaseTypeName != "string";
            if (isRequired)
            {
                builder.AppendLine($"if (_{member.MemberName}Index < 0 && !_allowMissingColumns)");
                builder.AppendLine("{");
                builder.Indent();
                builder.AppendLine($"throw new {EXCEPTION_TYPE}({ERROR_CODE_TYPE}.ParseError, \"Required column '{member.HeaderName}' not found in header row.\", rowNumber, 0);");
                builder.Unindent();
                builder.AppendLine("}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("_resolved = true;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitBindMethod(SourceBuilder builder, string fullyQualifiedName)
    {
        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"public {fullyQualifiedName}? Bind({ROW_TYPE} row, int rowNumber)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"var instance = new {fullyQualifiedName}();");
        builder.AppendLine("BindInto(instance, row, rowNumber);");
        builder.AppendLine("return instance;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitBindIntoMethod(SourceBuilder builder, string fullyQualifiedName, IReadOnlyList<MemberDescriptor> members)
    {
        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"public bool BindInto({fullyQualifiedName} instance, {ROW_TYPE} row, int rowNumber)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var columnCount = row.ColumnCount;");
        builder.AppendLine();

        foreach (var member in members)
        {
            EmitInlinePropertyBinding(builder, member);
        }

        builder.AppendLine("return true;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitInlinePropertyBinding(SourceBuilder builder, MemberDescriptor member)
    {
        var indexField = $"_{member.MemberName}Index";
        var isRequired = !member.IsNullable && member.BaseTypeName != "string";

        builder.AppendLine($"if ((uint){indexField} < (uint)columnCount)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"var span = row[{indexField}].CharSpan;");

        // Check for null values if configured
        builder.AppendLine("if (_nullValues is null || !IsNullValue(span, _nullValues))");
        builder.AppendLine("{");
        builder.Indent();

        // Emit inline parsing logic
        EmitInlineParsingLogic(builder, member);

        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");

        // Required column check for missing data
        if (isRequired)
        {
            builder.AppendLine($"else if ({indexField} >= 0 && !_allowMissingColumns)");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"throw new {EXCEPTION_TYPE}({ERROR_CODE_TYPE}.ParseError, $\"Row has only {{columnCount}} columns but '{member.HeaderName}' expects index {{{indexField}}}.\", rowNumber, {indexField} + 1);");
            builder.Unindent();
            builder.AppendLine("}");
        }
        builder.AppendLine();
    }

    private static void EmitInlineParsingLogic(SourceBuilder builder, MemberDescriptor member)
    {
        var baseType = member.BaseTypeName;
        var propertyName = member.MemberName;

        switch (baseType)
        {
            case "string":
                builder.AppendLine($"instance.{propertyName} = new string(span);");
                break;

            case "int":
            case "System.Int32":
                EmitInlineNumericParsing(builder, member, "int", "Integer");
                break;

            case "long":
            case "System.Int64":
                EmitInlineNumericParsing(builder, member, "long", "Integer");
                break;

            case "short":
            case "System.Int16":
                EmitInlineNumericParsing(builder, member, "short", "Integer");
                break;

            case "byte":
            case "System.Byte":
                EmitInlineNumericParsing(builder, member, "byte", "Integer");
                break;

            case "uint":
            case "System.UInt32":
                EmitInlineNumericParsing(builder, member, "uint", "Integer");
                break;

            case "ulong":
            case "System.UInt64":
                EmitInlineNumericParsing(builder, member, "ulong", "Integer");
                break;

            case "ushort":
            case "System.UInt16":
                EmitInlineNumericParsing(builder, member, "ushort", "Integer");
                break;

            case "sbyte":
            case "System.SByte":
                EmitInlineNumericParsing(builder, member, "sbyte", "Integer");
                break;

            case "decimal":
            case "System.Decimal":
                EmitInlineNumericParsing(builder, member, "decimal", "Number");
                break;

            case "double":
            case "System.Double":
                EmitInlineFloatParsing(builder, member, "double");
                break;

            case "float":
            case "System.Single":
                EmitInlineFloatParsing(builder, member, "float");
                break;

            case "bool":
            case "System.Boolean":
                EmitInlineBooleanParsing(builder, member);
                break;

            case "System.DateTime":
                EmitInlineDateTimeParsing(builder, member, "DateTime");
                break;

            case "System.DateTimeOffset":
                EmitInlineDateTimeParsing(builder, member, "DateTimeOffset");
                break;

            case "System.DateOnly":
                EmitInlineDateTimeParsing(builder, member, "DateOnly");
                break;

            case "System.TimeOnly":
                EmitInlineDateTimeParsing(builder, member, "TimeOnly");
                break;

            case "System.Guid":
                EmitInlineGuidParsing(builder, member);
                break;

            default:
                if (member.IsEnum)
                {
                    EmitInlineEnumParsing(builder, member);
                }
                else
                {
                    builder.AppendLine($"instance.{propertyName} = new string(span);");
                }
                break;
        }
    }

    private static void EmitInlineNumericParsing(SourceBuilder builder, MemberDescriptor member, string typeName, string numberStyle)
    {
        var propertyName = member.MemberName;
        var indexField = $"_{propertyName}Index";
        var isNullable = member.IsNullable;
        var styles = numberStyle == "Integer" ? "NumberStyles.Integer" : "NumberStyles.Number";

        builder.AppendLine($"if ({typeName}.TryParse(span, {styles}, _culture, out var parsed_{propertyName}))");
        builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
        if (!isNullable)
        {
            builder.AppendLine($"else if (!span.IsEmpty)");
            builder.AppendLine($"    throw CreateParseException(span, \"{member.HeaderName}\", rowNumber, {indexField});");
        }
    }

    private static void EmitInlineFloatParsing(SourceBuilder builder, MemberDescriptor member, string typeName)
    {
        var propertyName = member.MemberName;
        var indexField = $"_{propertyName}Index";
        var isNullable = member.IsNullable;
        const string STYLES = "NumberStyles.Float | NumberStyles.AllowThousands";

        builder.AppendLine($"if ({typeName}.TryParse(span, {STYLES}, _culture, out var parsed_{propertyName}))");
        builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
        if (!isNullable)
        {
            builder.AppendLine($"else if (!span.IsEmpty)");
            builder.AppendLine($"    throw CreateParseException(span, \"{member.HeaderName}\", rowNumber, {indexField});");
        }
    }

    private static void EmitInlineBooleanParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var indexField = $"_{propertyName}Index";
        var isNullable = member.IsNullable;

        builder.AppendLine($"if (bool.TryParse(span, out var parsed_{propertyName}))");
        builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
        if (!isNullable)
        {
            builder.AppendLine($"else if (!span.IsEmpty)");
            builder.AppendLine($"    throw CreateParseException(span, \"{member.HeaderName}\", rowNumber, {indexField});");
        }
    }

    private static void EmitInlineDateTimeParsing(SourceBuilder builder, MemberDescriptor member, string typeName)
    {
        var propertyName = member.MemberName;
        var indexField = $"_{propertyName}Index";
        var format = member.Format;
        var isNullable = member.IsNullable;

        if (format != null)
        {
            builder.AppendLine($"if ({typeName}.TryParseExact(span, \"{EscapeString(format)}\", _culture, DateTimeStyles.None, out var parsed_{propertyName}))");
        }
        else
        {
            builder.AppendLine($"if ({typeName}.TryParse(span, _culture, DateTimeStyles.None, out var parsed_{propertyName}))");
        }
        builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
        if (!isNullable)
        {
            builder.AppendLine($"else if (!span.IsEmpty)");
            builder.AppendLine($"    throw CreateParseException(span, \"{member.HeaderName}\", rowNumber, {indexField});");
        }
    }

    private static void EmitInlineGuidParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var indexField = $"_{propertyName}Index";
        var isNullable = member.IsNullable;

        builder.AppendLine($"if (Guid.TryParse(span, out var parsed_{propertyName}))");
        builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
        if (!isNullable)
        {
            builder.AppendLine($"else if (!span.IsEmpty)");
            builder.AppendLine($"    throw CreateParseException(span, \"{member.HeaderName}\", rowNumber, {indexField});");
        }
    }

    private static void EmitInlineEnumParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var indexField = $"_{propertyName}Index";
        var enumType = member.TypeofTypeName;
        var isNullable = member.IsNullable;

        builder.AppendLine($"if (Enum.TryParse<{enumType}>(span, ignoreCase: true, out var parsed_{propertyName}))");
        builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
        if (!isNullable)
        {
            builder.AppendLine($"else if (!span.IsEmpty)");
            builder.AppendLine($"    throw CreateParseException(span, \"{member.HeaderName}\", rowNumber, {indexField});");
        }
    }

    private static void EmitFindHeaderIndexMethod(SourceBuilder builder)
    {
        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"private static int FindHeaderIndex({ROW_TYPE} headerRow, string name, StringComparer comparer)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var count = headerRow.ColumnCount;");
        builder.AppendLine("for (int i = 0; i < count; i++)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("if (comparer.Equals(new string(headerRow[i].CharSpan), name))");
        builder.AppendLine("    return i;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine("return -1;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitIsNullValueMethod(SourceBuilder builder)
    {
        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine("private static bool IsNullValue(ReadOnlySpan<char> value, HashSet<string> nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("return nullValues.Contains(new string(value));");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitCreateParseExceptionMethod(SourceBuilder builder)
    {
        builder.AppendLine("private static Exception CreateParseException(ReadOnlySpan<char> value, string columnName, int rowNumber, int columnIndex)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var fieldValue = value.Length > 100 ? new string(value[..100]) + \"...\" : new string(value);");
        builder.AppendLine($"return new {EXCEPTION_TYPE}({ERROR_CODE_TYPE}.ParseError, $\"Failed to parse '{{columnName}}' at row {{rowNumber}}, column {{columnIndex + 1}}. Value: '{{fieldValue}}'\", rowNumber, columnIndex + 1, fieldValue);");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitRegistration(SourceProductionContext context, IReadOnlyList<TypeDescriptor> descriptors)
    {
        var builder = new SourceBuilder(8192);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GENERATED_NAMESPACE};");
        builder.AppendLine();
        builder.AppendLine("file static class CsvRecordBinderGeneratedRegistration");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("[ModuleInitializer]");
        builder.AppendLine("internal static void Register()");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var descriptor in descriptors)
        {
            // Filter members for binder (those with setters)
            var binderMembers = GetMembersWithSetters(descriptor.Members);
            if (binderMembers.Count > 0)
            {
                // Register descriptor-based binder for performance
                EmitTypedBinderRegistration(builder, descriptor.FullyQualifiedName, descriptor.SafeClassName);
            }

            // Filter members for writer (those with getters)
            var writerMembers = GetMembersWithGetters(descriptor.Members);
            if (writerMembers.Count > 0)
            {
                EmitWriterRegistration(builder, descriptor.FullyQualifiedName, writerMembers);
            }
        }

        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");

        context.AddSource("CsvRecordBinderFactory.Registration.g.cs", builder.ToString());
    }

    private static void EmitTypedBinderRegistration(SourceBuilder builder, string fullyQualifiedName, string safeClassName)
    {
        var binderClassName = $"CsvInlineBinder_{safeClassName}";
        builder.AppendLine($"{BINDER_FACTORY_TYPE}.RegisterBinder<{fullyQualifiedName}>({binderClassName}.Create);");
    }

    private static List<MemberDescriptor> GetMembersWithSetters(IReadOnlyList<MemberDescriptor> members)
    {
        var result = new List<MemberDescriptor>(members.Count);
        foreach (var m in members)
        {
            if (m.SetterFactory != null)
                result.Add(m);
        }
        return result;
    }

    private static List<MemberDescriptor> GetMembersWithGetters(IReadOnlyList<MemberDescriptor> members)
    {
        var result = new List<MemberDescriptor>(members.Count);
        foreach (var m in members)
        {
            if (m.GetterFactory != null)
                result.Add(m);
        }
        return result;
    }

    private static void EmitWriterRegistration(SourceBuilder builder, string fullyQualifiedName, IReadOnlyList<MemberDescriptor> members)
    {
        builder.AppendLine($"{WRITER_FACTORY_TYPE}.RegisterGeneratedWriter(typeof({fullyQualifiedName}), options => {WRITER_TYPE}<{fullyQualifiedName}>.CreateFromTemplates(options, new {WRITER_TYPE}<{fullyQualifiedName}>.WriterTemplate[]");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var member in members)
        {
            builder.AppendLine($"new {WRITER_TYPE}<{fullyQualifiedName}>.WriterTemplate(");
            builder.Indent();
            builder.AppendLine($"\"{member.MemberName}\",");
            builder.AppendLine($"typeof({member.TypeofTypeName}),");
            builder.AppendLine($"\"{member.HeaderName}\",");
            builder.AppendLine(member.AttributeIndex is null ? "null," : $"{member.AttributeIndex},");
            builder.AppendLine(member.Format is null ? "null," : $"\"{member.Format}\",");
            builder.AppendLine($"{member.GetterFactory}),");
            builder.Unindent();
        }

        builder.Unindent();
        builder.AppendLine("}));");
        builder.AppendLine();
    }

    private static TypeDescriptor? BuildDescriptor(INamedTypeSymbol type, CancellationToken ct)
    {
        var members = new List<MemberDescriptor>();
        var diagnostics = new List<Diagnostic>();

        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            ct.ThrowIfCancellationRequested();

            if (property.IsStatic)
                continue;

            var hasSetter = property.SetMethod is { DeclaredAccessibility: Accessibility.Public };
            var hasGetter = property.GetMethod is { DeclaredAccessibility: Accessibility.Public };

            if (!hasSetter && !hasGetter)
                continue;

            var mapAttribute = GetFirstMatchingAttribute(property, columnAttributeNames);
            var headerName = property.Name;
            int? attributeIndex = null;
            string? format = null;

            if (mapAttribute is not null)
            {
#pragma warning disable IDE0010 // Populate switch - intentionally not exhaustive
                foreach (var arg in mapAttribute.NamedArguments)
                {
                    switch (arg.Key)
                    {
                        case "Name" when arg.Value.Value is string s && !string.IsNullOrWhiteSpace(s):
                            headerName = s;
                            break;
                        case "Index" when arg.Value.Value is int i && i >= 0:
                            attributeIndex = i;
                            break;
                        case "Format" when arg.Value.Value is string f && !string.IsNullOrWhiteSpace(f):
                            format = f;
                            break;
                    }
                }
#pragma warning restore IDE0010
            }

            if (!IsSupportedType(property.Type))
            {
                diagnostics.Add(Diagnostic.Create(
                    unsupportedPropertyTypeDiagnostic,
                    property.Locations.FirstOrDefault() ?? Location.None,
                    property.Name,
                    property.Type.ToDisplayString()));
                continue;
            }

            var typeName = property.Type.ToDisplayString(FullyQualifiedFormatWithNullable);
            var typeofTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var headerLiteral = EscapeString(headerName);
            var formatLiteral = format != null ? EscapeString(format) : null;

            var (baseTypeName, isNullable, isEnum) = GetBaseTypeInfo(property.Type);
            var isReadOnlyMemoryChar = IsReadOnlyMemoryChar(property.Type);

            var setterFactory = hasSetter ? CreateSetter(typeName, type, property.Name) : null;
            var getterFactory = hasGetter ? CreateGetter(type, property.Name) : null;

            members.Add(new MemberDescriptor(
                property.Name,
                headerLiteral,
                attributeIndex,
                typeName,
                typeofTypeName,
                formatLiteral,
                setterFactory,
                getterFactory,
                baseTypeName,
                isNullable,
                isEnum,
                isReadOnlyMemoryChar));
        }

        if (members.Count == 0 && diagnostics.Count == 0)
            return null;

        var fqName = type.ToDisplayString(FullyQualifiedFormatWithNullable);
        var safeClassName = CreateSafeClassName(type);
        return new TypeDescriptor(fqName, safeClassName, members, diagnostics);
    }

    private static (string baseTypeName, bool isNullable, bool isEnum) GetBaseTypeInfo(ITypeSymbol type)
    {
        var isNullable = false;
        var actualType = type;

        if (type is INamedTypeSymbol { IsGenericType: true, Name: "Nullable" } nullable)
        {
            isNullable = true;
            actualType = nullable.TypeArguments[0];
        }

        if (type.NullableAnnotation == NullableAnnotation.Annotated && type.OriginalDefinition.SpecialType == SpecialType.None)
        {
            isNullable = true;
        }

        var isEnum = actualType.TypeKind == TypeKind.Enum;
        var baseTypeName = actualType.ToDisplayString();

        return (baseTypeName, isNullable, isEnum);
    }

    private static string CreateSetter(string typeName, INamedTypeSymbol type, string propertyName)
        => $"({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} target, object? val) => target.{propertyName} = ({typeName})val!";

    private static string CreateGetter(INamedTypeSymbol type, string propertyName)
        => $"({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} target) => target.{propertyName}";

    private sealed record TypeDescriptor(
        string FullyQualifiedName,
        string SafeClassName,
        IReadOnlyList<MemberDescriptor> Members,
        IReadOnlyList<Diagnostic> Diagnostics);

    private sealed record MemberDescriptor(
        string MemberName,
        string HeaderName,
        int? AttributeIndex,
        string TypeName,
        string TypeofTypeName,
        string? Format,
        string? SetterFactory,
        string? GetterFactory,
        string BaseTypeName,
        bool IsNullable,
        bool IsEnum,
        bool IsReadOnlyMemoryChar);
}
