using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using static HeroParser.Generators.GeneratorHelpers;

namespace HeroParser.Generators;

/// <summary>
/// Source generator for fixed-width record descriptors.
/// Generates property descriptors for high-performance binding via FixedWidthDescriptorBinder{T}.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FixedWidthRecordBinderGenerator : IIncrementalGenerator
{
    private const string GENERATED_NAMESPACE = "HeroParser.FixedWidths.Records.Binding";
    private const string BINDER_FACTORY_TYPE = "global::HeroParser.FixedWidths.Records.Binding.FixedWidthRecordBinderFactory";
    private const string WRITER_TYPE = "global::HeroParser.FixedWidths.Writing.FixedWidthRecordWriter";
    private const string WRITER_FACTORY_TYPE = "global::HeroParser.FixedWidths.Writing.FixedWidthRecordWriterFactory";
    private const string FIELD_ALIGNMENT_TYPE = "global::HeroParser.FieldAlignment";
    private const string DESCRIPTOR_TYPE = "global::HeroParser.FixedWidths.Records.Binding.FixedWidthRecordDescriptor";
    private const string PROPERTY_DESCRIPTOR_TYPE = "global::HeroParser.FixedWidths.Records.Binding.FixedWidthPropertyDescriptor";
    private const string BINDER_INTERFACE_TYPE = "global::HeroParser.FixedWidths.Records.Binding.IFixedWidthBinder";
    private const string BYTE_BINDER_INTERFACE_TYPE = "global::HeroParser.FixedWidths.Records.Binding.IFixedWidthByteBinder";

    private static readonly string[] generateAttributeNames =
    [
        "HeroParser.GenerateBinderAttribute"
    ];

    private static readonly string[] columnAttributeNames =
    [
        "HeroParser.PositionalMapAttribute"
    ];

    private static readonly string[] parseAttributeNames = ["HeroParser.ParseAttribute"];
    private static readonly string[] validateAttributeNames = ["HeroParser.ValidateAttribute"];

#pragma warning disable RS2008 // Enable analyzer release tracking - not needed for internal generator
    private static readonly DiagnosticDescriptor unsupportedPropertyTypeDiagnostic = new(
        "HERO002",
        "Unsupported property type",
        "Property '{0}' of type '{1}' is not supported by the fixed-width record binder generator. Supported types include primitives, DateTime, DateTimeOffset, DateOnly, TimeOnly, Guid, and enums.",
        "HeroParser.Generators",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

#pragma warning restore RS2008

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Use ForAttributeWithMetadataName for better caching
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                generateAttributeNames[0],
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, ct) => TransformToDescriptor(ctx, ct))
            .Where(static x => x is not null);

        // Generate per-type descriptor files for better incrementality
        context.RegisterSourceOutput(provider, static (spc, descriptor) => EmitDescriptor(spc, descriptor!));

        // Generate registration file
        context.RegisterSourceOutput(provider.Collect(), static (spc, descriptors) =>
        {
            var all = descriptors.Where(x => x is not null).ToList();
            if (all.Count > 0)
                EmitRegistration(spc, all!);
        });
    }

    private static TypeDescriptor? TransformToDescriptor(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract || !IsTypeAccessible(symbol))
            return null;

        return BuildDescriptor(symbol, ct);
    }

    private static void EmitDescriptor(SourceProductionContext context, TypeDescriptor descriptor)
    {
        // Report diagnostics
        foreach (var diag in descriptor.Diagnostics)
        {
            context.ReportDiagnostic(diag);
        }

        var binderMembers = GetMembersWithSetters(descriptor.Members);
        if (binderMembers.Count == 0)
            return;

        var builder = new SourceBuilder(16384);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using System.Text;");
        builder.AppendLine("using HeroParser.Validation;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GENERATED_NAMESPACE};");
        builder.AppendLine();

        // Emit descriptor class for optimized binding (writer + descriptor registration)
        EmitDescriptorClass(builder, descriptor.FullyQualifiedName, descriptor.SafeClassName, binderMembers);

        // Emit generated binder class for inline validation support
        EmitGeneratedBinderClass(builder, descriptor.FullyQualifiedName, descriptor.SafeClassName, binderMembers);
        EmitGeneratedByteBinderClass(builder, descriptor.FullyQualifiedName, descriptor.SafeClassName, binderMembers);

        context.AddSource($"FixedWidthDescriptor.{descriptor.SafeClassName}.g.cs", builder.ToString());
    }

    private static void EmitDescriptorClass(SourceBuilder builder, string fullyQualifiedName, string safeClassName, IReadOnlyList<MemberDescriptor> members)
    {
        var descriptorClassName = $"FixedWidthDescriptor_{safeClassName}";

        builder.AppendLine($"internal static class {descriptorClassName}");
        builder.AppendLine("{");
        builder.Indent();

        // Emit static setter methods for each property
        foreach (var member in members)
        {
            EmitPropertySetterMethod(builder, fullyQualifiedName, member);
        }
        builder.AppendLine();

        // Emit static descriptor instance using Lazy<T> for thread-safe initialization
        builder.AppendLine($"private static readonly global::System.Lazy<{DESCRIPTOR_TYPE}<{fullyQualifiedName}>> _instance = new(CreateDescriptor);");
        builder.AppendLine();

        // Emit GetDescriptor method that returns the cached descriptor
        builder.AppendLine($"public static {DESCRIPTOR_TYPE}<{fullyQualifiedName}> GetDescriptor() => _instance.Value;");
        builder.AppendLine();

        // Emit CreateDescriptor method that builds the descriptor
        builder.AppendLine($"private static {DESCRIPTOR_TYPE}<{fullyQualifiedName}> CreateDescriptor()");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"var properties = new {PROPERTY_DESCRIPTOR_TYPE}<{fullyQualifiedName}>[]");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var member in members)
        {
            var isRequired = !member.IsNullable && member.BaseTypeName != "string";
            builder.AppendLine($"new {PROPERTY_DESCRIPTOR_TYPE}<{fullyQualifiedName}>(" +
                $"\"{member.MemberName}\", " +
                $"{member.Start}, " +
                $"{member.Length}, " +
                $"'{EscapeChar(member.PadChar)}', " +
                $"{FIELD_ALIGNMENT_TYPE}.{member.Alignment}, " +
                $"Set_{member.MemberName}, " +
                $"{(isRequired ? "true" : "false")}),");
        }

        builder.Unindent();
        builder.AppendLine("};");
        builder.AppendLine($"return new {DESCRIPTOR_TYPE}<{fullyQualifiedName}>(properties);");
        builder.Unindent();
        builder.AppendLine("}");

        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitPropertySetterMethod(SourceBuilder builder, string fullyQualifiedName, MemberDescriptor member)
    {
        builder.AppendLine($"private static void Set_{member.MemberName}(ref {fullyQualifiedName} instance, ReadOnlySpan<char> span, CultureInfo culture)");
        builder.AppendLine("{");
        builder.Indent();

        // Emit parsing logic based on type
        EmitSetterParsingLogic(builder, member);

        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    #region Generated Binder Class (inline validation)

    private static void EmitGeneratedBinderClass(SourceBuilder builder, string fullyQualifiedName, string safeClassName, IReadOnlyList<MemberDescriptor> members)
    {
        var binderClassName = $"FixedWidthGeneratedBinder_{safeClassName}";

        builder.AppendLine($"internal sealed class {binderClassName} : {BINDER_INTERFACE_TYPE}<{fullyQualifiedName}>");
        builder.AppendLine("{");
        builder.Indent();

        // Emit static Regex fields for Pattern validation
        foreach (var member in members)
        {
            if (member.ValidationPattern != null)
            {
                var escapedPattern = EscapeString(member.ValidationPattern);
                builder.AppendLine($"private static readonly global::System.Text.RegularExpressions.Regex _pattern_{member.MemberName} = new(\"{escapedPattern}\", global::System.Text.RegularExpressions.RegexOptions.Compiled, TimeSpan.FromMilliseconds({member.ValidationPatternTimeoutMs}));");
            }
        }

        // Fields
        builder.AppendLine("private readonly CultureInfo _culture;");
        builder.AppendLine("private readonly HashSet<string>? _nullValues;");
        builder.AppendLine();

        // Constructor
        builder.AppendLine($"public {binderClassName}(CultureInfo? culture, IReadOnlyList<string>? nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("_culture = culture ?? CultureInfo.InvariantCulture;");
        builder.AppendLine("_nullValues = nullValues is { Count: > 0 }");
        builder.AppendLine("    ? new HashSet<string>(nullValues, StringComparer.Ordinal)");
        builder.AppendLine("    : null;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // TryBind method
        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"public bool TryBind(global::HeroParser.FixedWidths.FixedWidthCharSpanRow row, out {fullyQualifiedName} result, List<ValidationError>? errors = null)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"result = new {fullyQualifiedName}();");
        builder.AppendLine("return BindInto(ref result, row, errors);");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // BindInto method with inline parsing + validation
        EmitGeneratedBindIntoMethod(builder, fullyQualifiedName, members);

        // Factory method
        builder.AppendLine($"public static {BINDER_INTERFACE_TYPE}<{fullyQualifiedName}> Create(CultureInfo? culture, IReadOnlyList<string>? nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"return new {binderClassName}(culture, nullValues);");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // IsNullValue helper
        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine("private static bool IsNullValue(ReadOnlySpan<char> value, HashSet<string> nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("return nullValues.Contains(new string(value));");
        builder.Unindent();
        builder.AppendLine("}");

        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitGeneratedBindIntoMethod(SourceBuilder builder, string fullyQualifiedName, IReadOnlyList<MemberDescriptor> members)
    {
        bool anyValidation = HasAnyValidation(members);

        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"public bool BindInto(ref {fullyQualifiedName} instance, global::HeroParser.FixedWidths.FixedWidthCharSpanRow row, List<ValidationError>? errors = null)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var cultureLocal = _culture;");
        builder.AppendLine("var nullVals = _nullValues;");
        builder.AppendLine("var rowNumber = row.RecordNumber;");

        if (anyValidation)
        {
            builder.AppendLine("bool valid = true;");
        }

        builder.AppendLine();

        foreach (var member in members)
        {
            EmitGeneratedPropertyBinding(builder, member);
        }

        builder.AppendLine(anyValidation ? "return valid;" : "return true;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitGeneratedByteBinderClass(SourceBuilder builder, string fullyQualifiedName, string safeClassName, IReadOnlyList<MemberDescriptor> members)
    {
        var binderClassName = $"FixedWidthGeneratedByteBinder_{safeClassName}";

        builder.AppendLine($"internal sealed class {binderClassName} : {BYTE_BINDER_INTERFACE_TYPE}<{fullyQualifiedName}>");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var member in members)
        {
            if (member.ValidationPattern != null)
            {
                var escapedPattern = EscapeString(member.ValidationPattern);
                builder.AppendLine($"private static readonly global::System.Text.RegularExpressions.Regex _byte_pattern_{member.MemberName} = new(\"{escapedPattern}\", global::System.Text.RegularExpressions.RegexOptions.Compiled, TimeSpan.FromMilliseconds({member.ValidationPatternTimeoutMs}));");
            }
        }

        builder.AppendLine("private readonly CultureInfo _culture;");
        builder.AppendLine("private readonly byte[][]? _nullValues;");
        builder.AppendLine();

        builder.AppendLine($"public {binderClassName}(CultureInfo? culture, IReadOnlyList<string>? nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("_culture = culture ?? CultureInfo.InvariantCulture;");
        builder.AppendLine("_nullValues = nullValues is { Count: > 0 }");
        builder.AppendLine("    ? CreateNullValuesUtf8(nullValues)");
        builder.AppendLine("    : null;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"public bool TryBind(global::HeroParser.FixedWidths.FixedWidthByteSpanRow row, out {fullyQualifiedName} result, List<ValidationError>? errors = null)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"result = new {fullyQualifiedName}();");
        builder.AppendLine("return BindInto(ref result, row, errors);");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        EmitGeneratedByteBindIntoMethod(builder, fullyQualifiedName, members);

        builder.AppendLine($"public static {BYTE_BINDER_INTERFACE_TYPE}<{fullyQualifiedName}> Create(CultureInfo? culture, IReadOnlyList<string>? nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"return new {binderClassName}(culture, nullValues);");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine("private static bool IsNullValue(ReadOnlySpan<byte> value, byte[][] nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("foreach (var nullValue in nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("if (value.SequenceEqual(nullValue))");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("return true;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine("return false;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        builder.AppendLine("private static byte[][] CreateNullValuesUtf8(IReadOnlyList<string> nullValues)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var encoded = new byte[nullValues.Count][];");
        builder.AppendLine("for (int i = 0; i < nullValues.Count; i++)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("encoded[i] = System.Text.Encoding.UTF8.GetBytes(nullValues[i]);");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine("return encoded;");
        builder.Unindent();
        builder.AppendLine("}");

        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitGeneratedByteBindIntoMethod(SourceBuilder builder, string fullyQualifiedName, IReadOnlyList<MemberDescriptor> members)
    {
        bool anyValidation = HasAnyValidation(members);

        builder.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"public bool BindInto(ref {fullyQualifiedName} instance, global::HeroParser.FixedWidths.FixedWidthByteSpanRow row, List<ValidationError>? errors = null)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var cultureLocal = _culture;");
        builder.AppendLine("var nullVals = _nullValues;");
        builder.AppendLine("var rowNumber = row.RecordNumber;");

        if (anyValidation)
        {
            builder.AppendLine("bool valid = true;");
        }

        builder.AppendLine();

        foreach (var member in members)
        {
            EmitGeneratedBytePropertyBinding(builder, member);
        }

        builder.AppendLine(anyValidation ? "return valid;" : "return true;");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitGeneratedBytePropertyBinding(SourceBuilder builder, MemberDescriptor member)
    {
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"var field = row.GetField({member.Start}, {member.Length}, (byte)'{EscapeChar(member.PadChar)}', {FIELD_ALIGNMENT_TYPE}.{member.Alignment});");
        builder.AppendLine("var utf8 = field.ByteSpan;");
        builder.AppendLine();
        builder.AppendLine("if (nullVals is null || !IsNullValue(utf8, nullVals))");
        builder.AppendLine("{");
        builder.Indent();

        EmitByteInlineParsingLogic(builder, member);

        if (HasAnyValidation(member))
        {
            EmitByteValidationChecks(builder, member);
        }

        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitGeneratedPropertyBinding(SourceBuilder builder, MemberDescriptor member)
    {
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"var field = row.GetField({member.Start}, {member.Length}, '{EscapeChar(member.PadChar)}', {FIELD_ALIGNMENT_TYPE}.{member.Alignment});");
        builder.AppendLine("var span = field.CharSpan;");
        builder.AppendLine();
        builder.AppendLine("if (nullVals is null || !IsNullValue(span, nullVals))");
        builder.AppendLine("{");
        builder.Indent();

        // Emit inline parsing (same logic as setter methods but inline)
        EmitInlineParsingLogic(builder, member);

        // Emit validation checks after parsing
        if (HasAnyValidation(member))
        {
            EmitValidationChecks(builder, member);
        }

        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitByteInlineParsingLogic(SourceBuilder builder, MemberDescriptor member)
    {
        var baseType = member.BaseTypeName;

#pragma warning disable IDE0010
        switch (baseType)
        {
            case "string":
                builder.AppendLine($"instance.{member.MemberName} = FixedWidthUtf8BindingHelper.Decode(utf8);");
                break;

            case "int":
            case "System.Int32":
                EmitByteNumericParsing(builder, member, "TryParseInt32", "int");
                break;

            case "long":
            case "System.Int64":
                EmitByteNumericParsing(builder, member, "TryParseInt64", "long");
                break;

            case "short":
            case "System.Int16":
                EmitByteNumericParsing(builder, member, "TryParseInt16", "short");
                break;

            case "byte":
            case "System.Byte":
                EmitByteNumericParsing(builder, member, "TryParseByte", "byte");
                break;

            case "decimal":
            case "System.Decimal":
                EmitByteNumericParsing(builder, member, "TryParseDecimal", "decimal");
                break;

            case "double":
            case "System.Double":
                EmitByteNumericParsing(builder, member, "TryParseDouble", "double");
                break;

            case "float":
            case "System.Single":
                EmitByteNumericParsing(builder, member, "TryParseSingle", "float");
                break;

            case "bool":
            case "System.Boolean":
                EmitByteBooleanParsing(builder, member);
                break;

            case "System.DateTime":
                EmitByteDateTimeParsing(builder, member, "DateTime");
                break;

            case "System.DateTimeOffset":
                EmitByteDateTimeParsing(builder, member, "DateTimeOffset");
                break;

            case "System.DateOnly":
                EmitByteDateTimeParsing(builder, member, "DateOnly");
                break;

            case "System.TimeOnly":
                EmitByteDateTimeParsing(builder, member, "TimeOnly");
                break;

            case "System.Guid":
                EmitByteGuidParsing(builder, member);
                break;

            default:
                if (member.IsEnum)
                {
                    EmitByteEnumParsing(builder, member);
                }
                else
                {
                    builder.AppendLine($"instance.{member.MemberName} = FixedWidthUtf8BindingHelper.Decode(utf8);");
                }
                break;
        }
#pragma warning restore IDE0010
    }

    private static void EmitByteNumericParsing(SourceBuilder builder, MemberDescriptor member, string helperMethod, string typeName)
    {
        var propertyName = member.MemberName;

        if (member.IsNullable)
        {
            builder.AppendLine("if (utf8.IsEmpty || FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8)) { /* null */ }");
            builder.AppendLine($"else if (FixedWidthUtf8BindingHelper.{helperMethod}(utf8, cultureLocal, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, typeName);
        }
        else
        {
            builder.AppendLine($"if (FixedWidthUtf8BindingHelper.{helperMethod}(utf8, cultureLocal, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8))");
            else
                builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, typeName);
        }
    }

    private static void EmitByteBooleanParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;

        if (member.IsNullable)
        {
            builder.AppendLine("if (utf8.IsEmpty || FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8)) { /* null */ }");
            builder.AppendLine($"else if (FixedWidthUtf8BindingHelper.TryParseBoolean(utf8, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, "bool");
        }
        else
        {
            builder.AppendLine($"if (FixedWidthUtf8BindingHelper.TryParseBoolean(utf8, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8))");
            else
                builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, "bool");
        }
    }

    private static void EmitByteDateTimeParsing(SourceBuilder builder, MemberDescriptor member, string typeName)
    {
        var propertyName = member.MemberName;
        var formatExpression = member.Format is null ? "null" : $"\"{EscapeString(member.Format)}\"";

        if (member.IsNullable)
        {
            builder.AppendLine("if (utf8.IsEmpty || FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8)) { /* null */ }");
            builder.AppendLine($"else if (FixedWidthUtf8BindingHelper.TryParse{typeName}(utf8, cultureLocal, {formatExpression}, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, typeName);
        }
        else
        {
            builder.AppendLine($"if (FixedWidthUtf8BindingHelper.TryParse{typeName}(utf8, cultureLocal, {formatExpression}, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8))");
            else
                builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, typeName);
        }
    }

    private static void EmitByteGuidParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;

        if (member.IsNullable)
        {
            builder.AppendLine("if (utf8.IsEmpty || FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8)) { /* null */ }");
            builder.AppendLine($"else if (FixedWidthUtf8BindingHelper.TryParseGuid(utf8, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, "Guid");
        }
        else
        {
            builder.AppendLine($"if (FixedWidthUtf8BindingHelper.TryParseGuid(utf8, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8))");
            else
                builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, "Guid");
        }
    }

    private static void EmitByteEnumParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var enumType = member.TypeofTypeName;

        if (member.IsNullable)
        {
            builder.AppendLine("if (utf8.IsEmpty || FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8)) { /* null */ }");
            builder.AppendLine($"else if (FixedWidthUtf8BindingHelper.TryParseEnum<{enumType}>(utf8, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, enumType);
        }
        else
        {
            builder.AppendLine($"if (FixedWidthUtf8BindingHelper.TryParseEnum<{enumType}>(utf8, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8))");
            else
                builder.AppendLine("else");
            EmitByteThrowParseError(builder, propertyName, enumType);
        }
    }

    private static void EmitByteValidationChecks(SourceBuilder builder, MemberDescriptor member)
    {
        if (member.ValidationNotNull)
        {
            builder.AppendLine("if (utf8.IsEmpty || FixedWidthUtf8BindingHelper.IsNullOrWhiteSpace(utf8))");
            builder.AppendLine("{");
            builder.Indent();
            EmitByteAddValidationError(builder, member, "NotNull", "Value is required");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        if (member.ValidationNotEmpty)
        {
            builder.AppendLine($"if (!utf8.IsEmpty && string.IsNullOrWhiteSpace(instance.{member.MemberName}))");
            builder.AppendLine("{");
            builder.Indent();
            EmitByteAddValidationError(builder, member, "NotEmpty", "Value must not be empty or whitespace");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        if (member.ValidationMaxLength >= 0)
        {
            builder.AppendLine($"if (instance.{member.MemberName} != null && instance.{member.MemberName}.Length > {member.ValidationMaxLength})");
            builder.AppendLine("{");
            builder.Indent();
            EmitByteAddValidationError(builder, member, "MaxLength", $"Value exceeds maximum length of {member.ValidationMaxLength}");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        if (member.ValidationMinLength >= 0)
        {
            builder.AppendLine($"if (instance.{member.MemberName} != null && instance.{member.MemberName}.Length < {member.ValidationMinLength})");
            builder.AppendLine("{");
            builder.Indent();
            EmitByteAddValidationError(builder, member, "MinLength", $"Value is shorter than minimum length of {member.ValidationMinLength}");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        if (!double.IsNaN(member.ValidationRangeMin) || !double.IsNaN(member.ValidationRangeMax))
        {
            var valueExpr = $"instance.{member.MemberName}";
            var conditions = new List<string>();
            if (!double.IsNaN(member.ValidationRangeMin))
                conditions.Add($"{valueExpr} < {FormatRangeLiteral(member.ValidationRangeMin, member.BaseTypeName)}");
            if (!double.IsNaN(member.ValidationRangeMax))
                conditions.Add($"{valueExpr} > {FormatRangeLiteral(member.ValidationRangeMax, member.BaseTypeName)}");

            builder.AppendLine($"if (!utf8.IsEmpty && ({string.Join(" || ", conditions)}))");
            builder.AppendLine("{");
            builder.Indent();
            var rangeMsg = FormatRangeMessage(member.ValidationRangeMin, member.ValidationRangeMax);
            EmitByteAddValidationError(builder, member, "Range", rangeMsg);
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        if (member.ValidationPattern != null)
        {
            builder.AppendLine($"if (instance.{member.MemberName} != null && !_byte_pattern_{member.MemberName}.IsMatch(instance.{member.MemberName}))");
            builder.AppendLine("{");
            builder.Indent();
            EmitByteAddValidationError(builder, member, "Pattern", "Value does not match pattern");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }
    }

    private static void EmitByteAddValidationError(SourceBuilder builder, MemberDescriptor member, string rule, string message)
    {
        builder.AppendLine("errors?.Add(new global::HeroParser.Validation.ValidationError");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("RowNumber = rowNumber,");
        builder.AppendLine($"ColumnIndex = {member.Start},");
        builder.AppendLine("ColumnName = null,");
        builder.AppendLine($"PropertyName = \"{member.MemberName}\",");
        builder.AppendLine($"Rule = \"{rule}\",");
        builder.AppendLine($"Message = \"{EscapeString(message)}\",");
        builder.AppendLine("RawValue = FixedWidthUtf8BindingHelper.Decode(utf8)");
        builder.Unindent();
        builder.AppendLine("});");
    }

    private static void EmitByteThrowParseError(SourceBuilder builder, string propertyName, string typeName)
    {
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("throw new global::HeroParser.FixedWidths.FixedWidthException(");
        builder.AppendLine("    global::HeroParser.FixedWidths.FixedWidthErrorCode.ParseError,");
        builder.AppendLine($"    $\"Failed to parse '{{FixedWidthUtf8BindingHelper.Decode(utf8)}}' for property '{propertyName}' as {typeName}.\");");
        builder.Unindent();
        builder.AppendLine("}");
    }

    private static void EmitInlineParsingLogic(SourceBuilder builder, MemberDescriptor member)
    {
        var baseType = member.BaseTypeName;

#pragma warning disable IDE0010 // Populate switch - intentionally not exhaustive
        switch (baseType)
        {
            case "string":
                builder.AppendLine($"instance.{member.MemberName} = new string(span);");
                break;

            case "int":
            case "System.Int32":
                EmitInlineNumericParsing(builder, member, "int", "Integer");
                break;

            case "long":
            case "System.Int64":
                EmitInlineNumericParsing(builder, member, "long", "Integer");
                break;

            case "short":
            case "System.Int16":
                EmitInlineNumericParsing(builder, member, "short", "Integer");
                break;

            case "byte":
            case "System.Byte":
                EmitInlineNumericParsing(builder, member, "byte", "Integer");
                break;

            case "decimal":
            case "System.Decimal":
                EmitInlineNumericParsing(builder, member, "decimal", "Number");
                break;

            case "double":
            case "System.Double":
                EmitInlineFloatParsing(builder, member, "double");
                break;

            case "float":
            case "System.Single":
                EmitInlineFloatParsing(builder, member, "float");
                break;

            case "bool":
            case "System.Boolean":
                EmitInlineBooleanParsing(builder, member);
                break;

            case "System.DateTime":
                EmitInlineDateTimeParsing(builder, member, "DateTime");
                break;

            case "System.DateTimeOffset":
                EmitInlineDateTimeParsing(builder, member, "DateTimeOffset");
                break;

            case "System.DateOnly":
                EmitInlineDateTimeParsing(builder, member, "DateOnly");
                break;

            case "System.TimeOnly":
                EmitInlineDateTimeParsing(builder, member, "TimeOnly");
                break;

            case "System.Guid":
                EmitInlineGuidParsing(builder, member);
                break;

            default:
                if (member.IsEnum)
                    EmitInlineEnumParsing(builder, member);
                else
                    builder.AppendLine($"instance.{member.MemberName} = new string(span);");
                break;
        }
#pragma warning restore IDE0010
    }

    private static void EmitInlineNumericParsing(SourceBuilder builder, MemberDescriptor member, string typeName, string numberStyle)
    {
        var propertyName = member.MemberName;
        var isNullable = member.IsNullable;
        var styles = numberStyle == "Integer" ? "NumberStyles.Integer" : "NumberStyles.Number";

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if ({typeName}.TryParse(span, {styles}, cultureLocal, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
        else
        {
            builder.AppendLine($"if ({typeName}.TryParse(span, {styles}, cultureLocal, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!(span.IsEmpty || span.IsWhiteSpace()))");
            else
                builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
    }

    private static void EmitInlineFloatParsing(SourceBuilder builder, MemberDescriptor member, string typeName)
    {
        var propertyName = member.MemberName;
        var isNullable = member.IsNullable;
        const string STYLES = "NumberStyles.Float | NumberStyles.AllowThousands";

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if ({typeName}.TryParse(span, {STYLES}, cultureLocal, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
        else
        {
            builder.AppendLine($"if ({typeName}.TryParse(span, {STYLES}, cultureLocal, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!(span.IsEmpty || span.IsWhiteSpace()))");
            else
                builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
    }

    private static void EmitInlineBooleanParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var isNullable = member.IsNullable;

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if (bool.TryParse(span, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine($"else if (span.Length == 1)");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"var c_{propertyName} = span[0];");
            builder.AppendLine($"if (c_{propertyName} is '1' or 'Y' or 'y' or 'T' or 't') instance.{propertyName} = true;");
            builder.AppendLine($"else if (c_{propertyName} is '0' or 'N' or 'n' or 'F' or 'f') instance.{propertyName} = false;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "bool");
            builder.Unindent();
            builder.AppendLine("}");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "bool");
        }
        else
        {
            builder.AppendLine($"if (bool.TryParse(span, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine($"else if (span.Length == 1)");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"var c_{propertyName} = span[0];");
            builder.AppendLine($"if (c_{propertyName} is '1' or 'Y' or 'y' or 'T' or 't') instance.{propertyName} = true;");
            builder.AppendLine($"else if (c_{propertyName} is '0' or 'N' or 'n' or 'F' or 'f') instance.{propertyName} = false;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "bool");
            builder.Unindent();
            builder.AppendLine("}");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!(span.IsEmpty || span.IsWhiteSpace()))");
            else
                builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "bool");
        }
    }

    private static void EmitInlineDateTimeParsing(SourceBuilder builder, MemberDescriptor member, string typeName)
    {
        var propertyName = member.MemberName;
        var format = member.Format;
        var isNullable = member.IsNullable;

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            if (format != null)
                builder.AppendLine($"else if ({typeName}.TryParseExact(span, \"{EscapeString(format)}\", cultureLocal, DateTimeStyles.None, out var parsed_{propertyName}))");
            else
                builder.AppendLine($"else if ({typeName}.TryParse(span, cultureLocal, DateTimeStyles.None, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
        else
        {
            if (format != null)
                builder.AppendLine($"if ({typeName}.TryParseExact(span, \"{EscapeString(format)}\", cultureLocal, DateTimeStyles.None, out var parsed_{propertyName}))");
            else
                builder.AppendLine($"if ({typeName}.TryParse(span, cultureLocal, DateTimeStyles.None, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!(span.IsEmpty || span.IsWhiteSpace()))");
            else
                builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
    }

    private static void EmitInlineGuidParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var isNullable = member.IsNullable;

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if (Guid.TryParse(span, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "Guid");
        }
        else
        {
            builder.AppendLine($"if (Guid.TryParse(span, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!(span.IsEmpty || span.IsWhiteSpace()))");
            else
                builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "Guid");
        }
    }

    private static void EmitInlineEnumParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var enumType = member.TypeofTypeName;
        var isNullable = member.IsNullable;

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if (Enum.TryParse<{enumType}>(span, ignoreCase: true, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, enumType);
        }
        else
        {
            builder.AppendLine($"if (Enum.TryParse<{enumType}>(span, ignoreCase: true, out var parsed_{propertyName}))");
            builder.AppendLine($"    instance.{propertyName} = parsed_{propertyName};");
            if (member.ValidationNotNull)
                builder.AppendLine("else if (!(span.IsEmpty || span.IsWhiteSpace()))");
            else
                builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, enumType);
        }
    }

    #region Validation Code Generation

    private static bool HasAnyValidation(MemberDescriptor member)
    {
        return member.ValidationNotNull || member.ValidationNotEmpty
            || member.ValidationMaxLength >= 0 || member.ValidationMinLength >= 0
            || !double.IsNaN(member.ValidationRangeMin) || !double.IsNaN(member.ValidationRangeMax)
            || member.ValidationPattern != null;
    }

    private static bool HasAnyValidation(IReadOnlyList<MemberDescriptor> members)
    {
        foreach (var m in members) if (HasAnyValidation(m)) return true;
        return false;
    }

    private static void EmitValidationChecks(SourceBuilder builder, MemberDescriptor member)
    {
        // NotNull validation
        if (member.ValidationNotNull)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace())");
            builder.AppendLine("{");
            builder.Indent();
            EmitAddValidationError(builder, member, "NotNull", "Value is required");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        // NotEmpty validation (string only)
        if (member.ValidationNotEmpty)
        {
            builder.AppendLine($"if (!span.IsEmpty && string.IsNullOrWhiteSpace(instance.{member.MemberName}))");
            builder.AppendLine("{");
            builder.Indent();
            EmitAddValidationError(builder, member, "NotEmpty", "Value must not be empty or whitespace");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        // MaxLength validation (string only)
        if (member.ValidationMaxLength >= 0)
        {
            builder.AppendLine($"if (instance.{member.MemberName} != null && instance.{member.MemberName}.Length > {member.ValidationMaxLength})");
            builder.AppendLine("{");
            builder.Indent();
            EmitAddValidationError(builder, member, "MaxLength", $"Value exceeds maximum length of {member.ValidationMaxLength}");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        // MinLength validation (string only)
        if (member.ValidationMinLength >= 0)
        {
            builder.AppendLine($"if (instance.{member.MemberName} != null && instance.{member.MemberName}.Length < {member.ValidationMinLength})");
            builder.AppendLine("{");
            builder.Indent();
            EmitAddValidationError(builder, member, "MinLength", $"Value is shorter than minimum length of {member.ValidationMinLength}");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        // Range validation (numeric only)
        if (!double.IsNaN(member.ValidationRangeMin) || !double.IsNaN(member.ValidationRangeMax))
        {
            var valueExpr = $"instance.{member.MemberName}";
            var conditions = new List<string>();
            if (!double.IsNaN(member.ValidationRangeMin))
                conditions.Add($"{valueExpr} < {FormatRangeLiteral(member.ValidationRangeMin, member.BaseTypeName)}");
            if (!double.IsNaN(member.ValidationRangeMax))
                conditions.Add($"{valueExpr} > {FormatRangeLiteral(member.ValidationRangeMax, member.BaseTypeName)}");

            builder.AppendLine($"if (!span.IsEmpty && ({string.Join(" || ", conditions)}))");
            builder.AppendLine("{");
            builder.Indent();
            var rangeMsg = FormatRangeMessage(member.ValidationRangeMin, member.ValidationRangeMax);
            EmitAddValidationError(builder, member, "Range", rangeMsg);
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }

        // Pattern validation (string only)
        if (member.ValidationPattern != null)
        {
            builder.AppendLine($"if (instance.{member.MemberName} != null && !_pattern_{member.MemberName}.IsMatch(instance.{member.MemberName}))");
            builder.AppendLine("{");
            builder.Indent();
            EmitAddValidationError(builder, member, "Pattern", "Value does not match pattern");
            builder.AppendLine("valid = false;");
            builder.Unindent();
            builder.AppendLine("}");
        }
    }

    private static void EmitAddValidationError(SourceBuilder builder, MemberDescriptor member, string rule, string message)
    {
        builder.AppendLine($"errors?.Add(new global::HeroParser.Validation.ValidationError");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"RowNumber = rowNumber,");
        builder.AppendLine($"ColumnIndex = {member.Start},");
        builder.AppendLine($"ColumnName = null,");
        builder.AppendLine($"PropertyName = \"{member.MemberName}\",");
        builder.AppendLine($"Rule = \"{rule}\",");
        builder.AppendLine($"Message = \"{EscapeString(message)}\",");
        builder.AppendLine($"RawValue = new string(span)");
        builder.Unindent();
        builder.AppendLine("});");
    }

    private static string FormatRangeLiteral(double value, string baseType)
    {
        return baseType switch
        {
            "decimal" or "System.Decimal" => $"{value}m",
            "float" or "System.Single" => $"{value}f",
            "double" or "System.Double" => $"{value}d",
            "long" or "System.Int64" => $"{(long)value}L",
            "ulong" or "System.UInt64" => $"{(ulong)value}UL",
            "int" or "System.Int32" => $"{(int)value}",
            "uint" or "System.UInt32" => $"{(uint)value}U",
            "short" or "System.Int16" => $"(short){(short)value}",
            "ushort" or "System.UInt16" => $"(ushort){(ushort)value}",
            "byte" or "System.Byte" => $"(byte){(byte)value}",
            "sbyte" or "System.SByte" => $"(sbyte){(sbyte)value}",
            _ => $"{value}"
        };
    }

    private static string FormatRangeMessage(double min, double max)
    {
        if (!double.IsNaN(min) && !double.IsNaN(max))
            return $"Value must be between {min} and {max}";
        if (!double.IsNaN(min))
            return $"Value must be >= {min}";
        return $"Value must be <= {max}";
    }

    #endregion

    #endregion

    private static void EmitSetterParsingLogic(SourceBuilder builder, MemberDescriptor member)
    {
        var baseType = member.BaseTypeName;

#pragma warning disable IDE0010 // Populate switch - intentionally not exhaustive
        switch (baseType)
        {
            case "string":
                builder.AppendLine($"instance.{member.MemberName} = new string(span);");
                break;

            case "int":
            case "System.Int32":
                EmitNumericParsing(builder, member, "int", "Integer");
                break;

            case "long":
            case "System.Int64":
                EmitNumericParsing(builder, member, "long", "Integer");
                break;

            case "short":
            case "System.Int16":
                EmitNumericParsing(builder, member, "short", "Integer");
                break;

            case "byte":
            case "System.Byte":
                EmitNumericParsing(builder, member, "byte", "Integer");
                break;

            case "decimal":
            case "System.Decimal":
                EmitNumericParsing(builder, member, "decimal", "Number");
                break;

            case "double":
            case "System.Double":
                EmitFloatParsing(builder, member, "double");
                break;

            case "float":
            case "System.Single":
                EmitFloatParsing(builder, member, "float");
                break;

            case "bool":
            case "System.Boolean":
                EmitBooleanParsing(builder, member);
                break;

            case "System.DateTime":
                EmitDateTimeParsing(builder, member, "DateTime");
                break;

            case "System.DateTimeOffset":
                EmitDateTimeParsing(builder, member, "DateTimeOffset");
                break;

            case "System.DateOnly":
                EmitDateTimeParsing(builder, member, "DateOnly");
                break;

            case "System.TimeOnly":
                EmitDateTimeParsing(builder, member, "TimeOnly");
                break;

            case "System.Guid":
                EmitGuidParsing(builder, member);
                break;

            default:
                if (member.IsEnum)
                {
                    EmitEnumParsing(builder, member, member.IsNullable);
                }
                else
                {
                    builder.AppendLine($"instance.{member.MemberName} = new string(span);");
                }
                break;
        }
#pragma warning restore IDE0010
    }

    private static void EmitFloatParsing(SourceBuilder builder, MemberDescriptor member, string typeName)
    {
        var propertyName = member.MemberName;
        var isNullable = member.IsNullable;
        const string STYLES = "NumberStyles.Float | NumberStyles.AllowThousands";

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if ({typeName}.TryParse(span, {STYLES}, culture, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
        else
        {
            builder.AppendLine($"if ({typeName}.TryParse(span, {STYLES}, culture, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
    }

    private static void EmitBooleanParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var isNullable = member.IsNullable;

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if (bool.TryParse(span, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine($"else if (span.Length == 1)");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"var c = span[0];");
            builder.AppendLine($"if (c is '1' or 'Y' or 'y' or 'T' or 't') instance.{propertyName} = true;");
            builder.AppendLine($"else if (c is '0' or 'N' or 'n' or 'F' or 'f') instance.{propertyName} = false;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "bool");
            builder.Unindent();
            builder.AppendLine("}");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "bool");
        }
        else
        {
            builder.AppendLine($"if (bool.TryParse(span, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine($"else if (span.Length == 1)");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"var c = span[0];");
            builder.AppendLine($"if (c is '1' or 'Y' or 'y' or 'T' or 't') instance.{propertyName} = true;");
            builder.AppendLine($"else if (c is '0' or 'N' or 'n' or 'F' or 'f') instance.{propertyName} = false;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "bool");
            builder.Unindent();
            builder.AppendLine("}");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "bool");
        }
    }

    private static void EmitDateTimeParsing(SourceBuilder builder, MemberDescriptor member, string typeName)
    {
        var propertyName = member.MemberName;
        var format = member.Format;
        var isNullable = member.IsNullable;

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            if (format != null)
            {
                builder.AppendLine($"else if ({typeName}.TryParseExact(span, \"{EscapeString(format)}\", culture, DateTimeStyles.None, out var parsed))");
            }
            else
            {
                builder.AppendLine($"else if ({typeName}.TryParse(span, culture, DateTimeStyles.None, out var parsed))");
            }
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
        else
        {
            if (format != null)
            {
                builder.AppendLine($"if ({typeName}.TryParseExact(span, \"{EscapeString(format)}\", culture, DateTimeStyles.None, out var parsed))");
            }
            else
            {
                builder.AppendLine($"if ({typeName}.TryParse(span, culture, DateTimeStyles.None, out var parsed))");
            }
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
    }

    private static void EmitGuidParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var isNullable = member.IsNullable;

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if (Guid.TryParse(span, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "Guid");
        }
        else
        {
            builder.AppendLine($"if (Guid.TryParse(span, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, "Guid");
        }
    }

    private static void EmitEnumParsing(SourceBuilder builder, MemberDescriptor member, bool isNullable)
    {
        var propertyName = member.MemberName;
        var enumType = member.TypeofTypeName;

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if (Enum.TryParse<{enumType}>(span, ignoreCase: true, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, enumType);
        }
        else
        {
            builder.AppendLine($"if (Enum.TryParse<{enumType}>(span, ignoreCase: true, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, enumType);
        }
    }

    private static void EmitNumericParsing(SourceBuilder builder, MemberDescriptor member, string typeName, string numberStyle)
    {
        var propertyName = member.MemberName;
        var isNullable = member.IsNullable;
        var styles = numberStyle == "Integer" ? "NumberStyles.Integer" : "NumberStyles.Number";

        if (isNullable)
        {
            builder.AppendLine($"if (span.IsEmpty || span.IsWhiteSpace()) {{ /* null */ }}");
            builder.AppendLine($"else if ({typeName}.TryParse(span, {styles}, culture, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
        else
        {
            builder.AppendLine($"if ({typeName}.TryParse(span, {styles}, culture, out var parsed))");
            builder.AppendLine($"    instance.{propertyName} = parsed;");
            builder.AppendLine("else");
            EmitThrowParseError(builder, propertyName, typeName);
        }
    }

    private static void EmitThrowParseError(SourceBuilder builder, string propertyName, string typeName)
    {
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("throw new global::HeroParser.FixedWidths.FixedWidthException(");
        builder.AppendLine("    global::HeroParser.FixedWidths.FixedWidthErrorCode.ParseError,");
        builder.AppendLine($"    $\"Failed to parse '{{new string(span)}}' for property '{propertyName}' as {typeName}.\");");
        builder.Unindent();
        builder.AppendLine("}");
    }

    private static void EmitRegistration(SourceProductionContext context, IReadOnlyList<TypeDescriptor> descriptors)
    {
        var builder = new SourceBuilder(8192);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GENERATED_NAMESPACE};");
        builder.AppendLine();
        builder.AppendLine("file static class FixedWidthRecordBinderGeneratedRegistration");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("[ModuleInitializer]");
        builder.AppendLine("internal static void Register()");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var descriptor in descriptors)
        {
            var binderMembers = GetMembersWithSetters(descriptor.Members);
            if (binderMembers.Count > 0)
            {
                EmitDescriptorRegistration(builder, descriptor.FullyQualifiedName, descriptor.SafeClassName);
                EmitGeneratedBinderRegistration(builder, descriptor.FullyQualifiedName, descriptor.SafeClassName);
                EmitGeneratedByteBinderRegistration(builder, descriptor.FullyQualifiedName, descriptor.SafeClassName);
            }

            var writerMembers = GetMembersWithGetters(descriptor.Members);
            if (writerMembers.Count > 0)
            {
                EmitWriterRegistration(builder, descriptor.FullyQualifiedName, writerMembers);
            }
        }

        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");

        context.AddSource("FixedWidthRecordBinderFactory.Registration.g.cs", builder.ToString());
    }

    private static List<MemberDescriptor> GetMembersWithSetters(IReadOnlyList<MemberDescriptor> members)
    {
        var result = new List<MemberDescriptor>(members.Count);
        foreach (var m in members)
        {
            if (m.SetterFactory != null)
                result.Add(m);
        }
        return result;
    }

    private static List<MemberDescriptor> GetMembersWithGetters(IReadOnlyList<MemberDescriptor> members)
    {
        var result = new List<MemberDescriptor>(members.Count);
        foreach (var m in members)
        {
            if (m.GetterFactory != null)
                result.Add(m);
        }
        return result;
    }

    private static void EmitDescriptorRegistration(SourceBuilder builder, string fullyQualifiedName, string safeClassName)
    {
        var descriptorClassName = $"FixedWidthDescriptor_{safeClassName}";
        builder.AppendLine($"{BINDER_FACTORY_TYPE}.RegisterDescriptor<{fullyQualifiedName}>({descriptorClassName}.GetDescriptor);");
    }

    private static void EmitGeneratedBinderRegistration(SourceBuilder builder, string fullyQualifiedName, string safeClassName)
    {
        var binderClassName = $"global::{GENERATED_NAMESPACE}.FixedWidthGeneratedBinder_{safeClassName}";
        builder.AppendLine($"{BINDER_FACTORY_TYPE}.RegisterGeneratedBinder<{fullyQualifiedName}>({binderClassName}.Create);");
    }

    private static void EmitGeneratedByteBinderRegistration(SourceBuilder builder, string fullyQualifiedName, string safeClassName)
    {
        var binderClassName = $"global::{GENERATED_NAMESPACE}.FixedWidthGeneratedByteBinder_{safeClassName}";
        builder.AppendLine($"{BINDER_FACTORY_TYPE}.RegisterGeneratedByteBinder<{fullyQualifiedName}>({binderClassName}.Create);");
    }

    private static void EmitWriterRegistration(SourceBuilder builder, string fullyQualifiedName, IReadOnlyList<MemberDescriptor> members)
    {
        builder.AppendLine($"{WRITER_FACTORY_TYPE}.RegisterGeneratedWriter(typeof({fullyQualifiedName}), options => {WRITER_TYPE}<{fullyQualifiedName}>.CreateFromTemplates(options, new {WRITER_TYPE}<{fullyQualifiedName}>.WriterTemplate[]");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var member in members)
        {
            builder.AppendLine($"new {WRITER_TYPE}<{fullyQualifiedName}>.WriterTemplate(");
            builder.Indent();
            builder.AppendLine($"\"{member.MemberName}\",");
            builder.AppendLine($"typeof({member.TypeofTypeName}),");
            builder.AppendLine($"{member.Start},");
            builder.AppendLine($"{member.Length},");
            builder.AppendLine($"{FIELD_ALIGNMENT_TYPE}.{member.Alignment},");
            builder.AppendLine($"'{EscapeChar(member.PadChar)}',");
            builder.AppendLine(member.Format is null ? "null," : $"\"{member.Format}\",");
            builder.AppendLine($"{member.GetterFactory}),");
            builder.Unindent();
        }

        builder.Unindent();
        builder.AppendLine("}));");
        builder.AppendLine();
    }

    private static TypeDescriptor? BuildDescriptor(INamedTypeSymbol type, CancellationToken ct)
    {
        var members = new List<MemberDescriptor>();
        var diagnostics = new List<Diagnostic>();

        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            ct.ThrowIfCancellationRequested();

            if (property.IsStatic)
                continue;

            var hasSetter = property.SetMethod is { DeclaredAccessibility: Accessibility.Public };
            var hasGetter = property.GetMethod is { DeclaredAccessibility: Accessibility.Public };

            if (!hasSetter && !hasGetter)
                continue;

            var mapAttribute = GetFirstMatchingAttribute(property, columnAttributeNames);
            if (mapAttribute is null)
                continue;

            // [PositionalMap] — Start, Length, End, PadChar, Alignment
            int start = 0;
            int length = 0;
            int end = -1;
            char padChar = '\0';
            string alignment = "Left";

#pragma warning disable IDE0010 // Populate switch - intentionally not exhaustive
            foreach (var arg in mapAttribute.NamedArguments)
            {
                switch (arg.Key)
                {
                    case "Start" when arg.Value.Value is int s:
                        start = s;
                        break;
                    case "Length" when arg.Value.Value is int l:
                        length = l;
                        break;
                    case "End" when arg.Value.Value is int e:
                        end = e;
                        break;
                    case "PadChar" when arg.Value.Value is char p:
                        padChar = p;
                        break;
                    case "Alignment" when arg.Value.Value is int a:
                        alignment = GetAlignmentName(a);
                        break;
                }
            }
#pragma warning restore IDE0010

            // If End is specified but Length is not, calculate Length from End - Start
            if (length == 0 && end > start)
                length = end - start;

            // [Parse] — Format
            string? format = null;
            var parseAttribute = GetFirstMatchingAttribute(property, parseAttributeNames);
            if (parseAttribute is not null)
            {
#pragma warning disable IDE0010 // Populate switch - intentionally not exhaustive
                foreach (var arg in parseAttribute.NamedArguments)
                {
                    switch (arg.Key)
                    {
                        case "Format" when arg.Value.Value is string f && !string.IsNullOrWhiteSpace(f):
                            format = f;
                            break;
                    }
                }
#pragma warning restore IDE0010
            }

            // [Validate] — NotNull, NotEmpty, MaxLength, MinLength, RangeMin, RangeMax, Pattern, PatternTimeoutMs
            bool validationRequired = false;
            bool validationNotEmpty = false;
            int validationMaxLength = -1;
            int validationMinLength = -1;
            double validationRangeMin = double.NaN;
            double validationRangeMax = double.NaN;
            string? validationPattern = null;
            int validationPatternTimeoutMs = 1000;
            var validateAttribute = GetFirstMatchingAttribute(property, validateAttributeNames);
            if (validateAttribute is not null)
            {
#pragma warning disable IDE0010 // Populate switch - intentionally not exhaustive
                foreach (var arg in validateAttribute.NamedArguments)
                {
                    switch (arg.Key)
                    {
                        case "NotNull" when arg.Value.Value is bool r:
                            validationRequired = r; break;
                        case "NotEmpty" when arg.Value.Value is bool ne:
                            validationNotEmpty = ne; break;
                        case "MaxLength" when arg.Value.Value is int ml && ml >= 0:
                            validationMaxLength = ml; break;
                        case "MinLength" when arg.Value.Value is int mnl && mnl >= 0:
                            validationMinLength = mnl; break;
                        case "RangeMin" when arg.Value.Value is double rmin && !double.IsNaN(rmin):
                            validationRangeMin = rmin; break;
                        case "RangeMax" when arg.Value.Value is double rmax && !double.IsNaN(rmax):
                            validationRangeMax = rmax; break;
                        case "Pattern" when arg.Value.Value is string pat && !string.IsNullOrWhiteSpace(pat):
                            validationPattern = pat; break;
                        case "PatternTimeoutMs" when arg.Value.Value is int pt && pt > 0:
                            validationPatternTimeoutMs = pt; break;
                    }
                }
#pragma warning restore IDE0010
            }

            if (!IsSupportedType(property.Type))
            {
                diagnostics.Add(Diagnostic.Create(
                    unsupportedPropertyTypeDiagnostic,
                    property.Locations.FirstOrDefault() ?? Location.None,
                    property.Name,
                    property.Type.ToDisplayString()));
                continue;
            }

            var typeName = property.Type.ToDisplayString(FullyQualifiedFormatWithNullable);
            var typeofTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var formatLiteral = format != null ? EscapeString(format) : null;

            var (baseTypeName, isNullable, isEnum) = GetBaseTypeInfo(property.Type);

            if (padChar == '\0')
                padChar = ' ';

            bool isStringType = baseTypeName is "string" or "string?";
            bool isNumericType = baseTypeName is "int" or "System.Int32" or "long" or "System.Int64"
                or "short" or "System.Int16" or "byte" or "System.Byte" or "uint" or "System.UInt32"
                or "ulong" or "System.UInt64" or "ushort" or "System.UInt16" or "sbyte" or "System.SByte"
                or "decimal" or "System.Decimal" or "double" or "System.Double" or "float" or "System.Single";

            if (validationNotEmpty && !isStringType)
            {
                diagnostics.Add(Diagnostic.Create(NotEmptyOnNonStringDiagnostic, property.Locations.FirstOrDefault() ?? Location.None, property.Name, baseTypeName));
                validationNotEmpty = false;
            }
            if ((validationMaxLength >= 0 || validationMinLength >= 0) && !isStringType)
            {
                diagnostics.Add(Diagnostic.Create(LengthOnNonStringDiagnostic, property.Locations.FirstOrDefault() ?? Location.None, property.Name, baseTypeName));
                validationMaxLength = -1;
                validationMinLength = -1;
            }
            if ((!double.IsNaN(validationRangeMin) || !double.IsNaN(validationRangeMax)) && !isNumericType)
            {
                diagnostics.Add(Diagnostic.Create(RangeOnNonNumericDiagnostic, property.Locations.FirstOrDefault() ?? Location.None, property.Name, baseTypeName));
                validationRangeMin = double.NaN;
                validationRangeMax = double.NaN;
            }
            if (validationPattern != null && !isStringType)
            {
                diagnostics.Add(Diagnostic.Create(PatternOnNonStringDiagnostic, property.Locations.FirstOrDefault() ?? Location.None, property.Name, baseTypeName));
                validationPattern = null;
            }

            var setterFactory = hasSetter ? CreateSetter(typeName, type, property.Name) : null;
            var getterFactory = hasGetter ? CreateGetter(type, property.Name) : null;

            members.Add(new MemberDescriptor(
                property.Name,
                start,
                length,
                padChar,
                alignment,
                typeName,
                typeofTypeName,
                formatLiteral,
                setterFactory,
                getterFactory,
                baseTypeName,
                isNullable,
                isEnum,
                validationRequired,
                validationNotEmpty,
                validationMaxLength,
                validationMinLength,
                validationRangeMin,
                validationRangeMax,
                validationPattern,
                validationPatternTimeoutMs));
        }

        if (members.Count == 0 && diagnostics.Count == 0)
            return null;

        // Sort by Start position
        members.Sort((a, b) => a.Start.CompareTo(b.Start));

        var fqName = type.ToDisplayString(FullyQualifiedFormatWithNullable);
        var safeClassName = CreateSafeClassName(type);
        return new TypeDescriptor(fqName, safeClassName, members, diagnostics);
    }

    private static (string baseTypeName, bool isNullable, bool isEnum) GetBaseTypeInfo(ITypeSymbol type)
    {
        var isNullable = false;
        var actualType = type;

        if (type is INamedTypeSymbol { IsGenericType: true, Name: "Nullable" } nullable)
        {
            isNullable = true;
            actualType = nullable.TypeArguments[0];
        }

        if (type.NullableAnnotation == NullableAnnotation.Annotated && type.OriginalDefinition.SpecialType == SpecialType.None)
        {
            isNullable = true;
        }

        var isEnum = actualType.TypeKind == TypeKind.Enum;
        var baseTypeName = actualType.ToDisplayString();

        return (baseTypeName, isNullable, isEnum);
    }

    private static string GetAlignmentName(int value)
    {
        return value switch
        {
            0 => "Left",
            1 => "Right",
            2 => "Center",
            3 => "None",
            _ => "Left"
        };
    }

    private static string CreateSetter(string typeName, INamedTypeSymbol type, string propertyName)
        => $"({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} target, object? val) => target.{propertyName} = ({typeName})val!";

    private static string CreateGetter(INamedTypeSymbol type, string propertyName)
        => $"({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} target) => target.{propertyName}";

    private sealed record TypeDescriptor(
        string FullyQualifiedName,
        string SafeClassName,
        IReadOnlyList<MemberDescriptor> Members,
        IReadOnlyList<Diagnostic> Diagnostics);

    private sealed record MemberDescriptor(
        string MemberName,
        int Start,
        int Length,
        char PadChar,
        string Alignment,
        string TypeName,
        string TypeofTypeName,
        string? Format,
        string? SetterFactory,
        string? GetterFactory,
        string BaseTypeName,
        bool IsNullable,
        bool IsEnum,
        // Validation fields:
        bool ValidationNotNull,
        bool ValidationNotEmpty,
        int ValidationMaxLength,       // -1 = unchecked
        int ValidationMinLength,       // -1 = unchecked
        double ValidationRangeMin,     // NaN = unchecked
        double ValidationRangeMax,     // NaN = unchecked
        string? ValidationPattern,
        int ValidationPatternTimeoutMs);  // default 1000

}
