using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using static HeroParser.Generators.GeneratorHelpers;

namespace HeroParser.Generators;

/// <summary>
/// Source generator for High-Throughput Tabular Binary (HTB) record binders and writers.
/// Generates zero-boxing, Native AOT-safe serialization and deserialization pathways.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class HtbRecordBinderGenerator : IIncrementalGenerator
{
    private const string GENERATED_NAMESPACE = "HeroParser.Htbs.Records";
    private const string BINDER_FACTORY_TYPE = "global::HeroParser.Htbs.Records.HtbRecordBinderFactory";
    private const string WRITER_FACTORY_TYPE = "global::HeroParser.Htbs.Records.HtbRecordWriterFactory";
    private const string BINDER_INTERFACE_TYPE = "global::HeroParser.Htbs.Records.IHtbBinder<";
    private const string WRITER_INTERFACE_TYPE = "global::HeroParser.Htbs.Records.IHtbWriter<";

    private static readonly string[] generateAttributeNames =
    [
        "HeroParser.GenerateBinderAttribute"
    ];

    private static readonly string[] columnAttributeNames =
    [
        "HeroParser.TabularMapAttribute"
    ];

    private enum HtbDataType : byte
    {
        Unknown = 0,
        Int32 = 1,
        Int64 = 2,
        Float = 3,
        Double = 4,
        Decimal = 5,
        Boolean = 6,
        DateTime = 7,
        String = 8,
        Guid = 9,
        FloatArray = 10
    }



    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Use ForAttributeWithMetadataName for better caching
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                generateAttributeNames[0],
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, ct) => TransformToDescriptor(ctx, ct))
            .Where(static x => x is not null);

        // Generate per-type typed binder files for better incrementality
        context.RegisterSourceOutput(provider, static (spc, descriptor) => EmitTypedBinder(spc, descriptor!));

        // Generate registration file
        context.RegisterSourceOutput(provider.Collect(), static (spc, descriptors) =>
        {
            var all = descriptors.Where(x => x is not null).ToList();
            if (all.Count > 0)
                EmitRegistration(spc, all!);
        });
    }

    private static TypeDescriptor? TransformToDescriptor(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract || !IsTypeAccessible(symbol))
            return null;

        return BuildDescriptor(symbol, ct);
    }

    private static void EmitTypedBinder(SourceProductionContext context, TypeDescriptor descriptor)
    {
        // Report diagnostics
        foreach (var diag in descriptor.Diagnostics)
        {
            context.ReportDiagnostic(diag);
        }

        var binderMembers = descriptor.Members;
        if (binderMembers.Count == 0)
            return;

        var builder = new SourceBuilder(16384);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Buffers.Binary;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using System.Text;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using HeroParser.Htbs.Reading;");
        builder.AppendLine("using HeroParser.Htbs.Writing;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GENERATED_NAMESPACE};");
        builder.AppendLine();

        var binderClassName = $"HtbInlineBinder_{descriptor.SafeClassName}";
        builder.AppendLine($"internal sealed class {binderClassName} : {BINDER_INTERFACE_TYPE}{descriptor.FullyQualifiedName}>, {WRITER_INTERFACE_TYPE}{descriptor.FullyQualifiedName}>");
        builder.AppendLine("{");
        builder.Indent();

        // Emit static Regex fields for Pattern validation
        foreach (var member in binderMembers)
        {
            if (member.ValidationPattern != null)
            {
                var escapedPattern = EscapeString(member.ValidationPattern);
                builder.AppendLine($"private static readonly System.Text.RegularExpressions.Regex _pattern_{member.MemberName} = new(\"{escapedPattern}\", System.Text.RegularExpressions.RegexOptions.None, TimeSpan.FromMilliseconds({member.ValidationPatternTimeoutMs}));");
            }
        }
        builder.AppendLine();

        // Emit index fields
        foreach (var member in binderMembers)
        {
            builder.AppendLine($"private int _{member.MemberName}Index = -1;");
        }
        builder.AppendLine();

        // Default parameterless constructor (used by Writer)
        builder.AppendLine($"public {binderClassName}()");
        builder.AppendLine("{");
        builder.AppendLine("}");
        builder.AppendLine();

        // Constructor with schema (used by Reader)
        builder.AppendLine($"public {binderClassName}(global::HeroParser.Htbs.Records.HtbSchema schema)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var cols = schema.Columns;");
        builder.AppendLine("for (int i = 0; i < cols.Count; i++)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var name = cols[i].Name;");
        for (int i = 0; i < binderMembers.Count; i++)
        {
            var member = binderMembers[i];
            builder.AppendLine($"{(i == 0 ? "if" : "else if")} (string.Equals(name, \"{member.HeaderName}\", StringComparison.OrdinalIgnoreCase)) _{member.MemberName}Index = i;");
        }
        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // Implement IsColumnBound
        builder.AppendLine("public bool IsColumnBound(int columnIndex)");
        builder.AppendLine("{");
        builder.Indent();
        var boundChecks = binderMembers.Select(m => $"columnIndex == _{m.MemberName}Index").ToList();
        if (boundChecks.Count > 0)
        {
            builder.AppendLine($"return columnIndex >= 0 && ({string.Join(" || ", boundChecks)});");
        }
        else
        {
            builder.AppendLine("return false;");
        }
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // Implement BindField
        builder.AppendLine($"public void BindField({descriptor.FullyQualifiedName} instance, int columnIndex, HtbRecordReader<{descriptor.FullyQualifiedName}> reader, bool isNull)");
        builder.AppendLine("{");
        builder.Indent();
        for (int i = 0; i < binderMembers.Count; i++)
        {
            var member = binderMembers[i];
            builder.AppendLine($"{(i == 0 ? "if" : "else if")} (columnIndex == _{member.MemberName}Index)");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine("if (isNull)");
            builder.AppendLine("{");
            builder.Indent();
            if (member.ValidationNotNull)
            {
                builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.DeserializationError, \"Property '{member.MemberName}' violated validation constraint: value cannot be null.\");");
            }
            else
            {
                if (member.IsNullable || member.BaseTypeName == "string" || member.BaseTypeName == "float[]")
                    builder.AppendLine($"instance.{member.MemberName} = default!;");
                else
                    builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.CorruptData, \"Column '{member.HeaderName}' is not nullable but null was read.\");");
            }
            builder.Unindent();
            builder.AppendLine("}");
            builder.AppendLine("else");
            builder.AppendLine("{");
            builder.Indent();
            EmitReadCall(builder, member, isAsync: false);
            EmitHtbValidationChecks(builder, member);
            builder.Unindent();
            builder.AppendLine("}");
            builder.Unindent();
            builder.AppendLine("}");
        }
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // Implement BindFieldAsync
        builder.AppendLine($"public async ValueTask BindFieldAsync({descriptor.FullyQualifiedName} instance, int columnIndex, HtbRecordReader<{descriptor.FullyQualifiedName}> reader, bool isNull)");
        builder.AppendLine("{");
        builder.Indent();
        for (int i = 0; i < binderMembers.Count; i++)
        {
            var member = binderMembers[i];
            builder.AppendLine($"{(i == 0 ? "if" : "else if")} (columnIndex == _{member.MemberName}Index)");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine("if (isNull)");
            builder.AppendLine("{");
            builder.Indent();
            if (member.ValidationNotNull)
            {
                builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.DeserializationError, \"Property '{member.MemberName}' violated validation constraint: value cannot be null.\");");
            }
            else
            {
                if (member.IsNullable || member.BaseTypeName == "string" || member.BaseTypeName == "float[]")
                    builder.AppendLine($"instance.{member.MemberName} = default!;");
                else
                    builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.CorruptData, \"Column '{member.HeaderName}' is not nullable but null was read.\");");
            }
            builder.Unindent();
            builder.AppendLine("}");
            builder.AppendLine("else");
            builder.AppendLine("{");
            builder.Indent();
            EmitReadCall(builder, member, isAsync: true);
            EmitHtbValidationChecks(builder, member);
            builder.Unindent();
            builder.AppendLine("}");
            builder.Unindent();
            builder.AppendLine("}");
        }
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // Implement WriteRecord (Synchronous - buffers directly)
        builder.AppendLine($"public void WriteRecord(HtbRecordWriter<{descriptor.FullyQualifiedName}> writer, {descriptor.FullyQualifiedName} record)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"int colCount = {binderMembers.Count};");
        builder.AppendLine("int maskLen = (colCount + 7) / 8;");
        builder.AppendLine("Span<byte> mask = stackalloc byte[maskLen];");
        builder.AppendLine("mask.Clear();");
        builder.AppendLine();

        // 1. Compute null bitmask
        for (int i = 0; i < binderMembers.Count; i++)
        {
            var member = binderMembers[i];
            if (member.IsNullable || member.BaseTypeName == "string" || member.BaseTypeName == "float[]")
            {
                builder.AppendLine($"if (record.{member.MemberName} == null)");
                builder.AppendLine("{");
                builder.Indent();
                builder.AppendLine($"mask[{i} / 8] |= (byte)(1 << ({i} % 8));");
                builder.Unindent();
                builder.AppendLine("}");
            }
        }
        builder.AppendLine();
        builder.AppendLine("writer.WriteMask(mask);");
        builder.AppendLine();

        // 2. Write non-null properties directly - ZERO boxing!
        for (int i = 0; i < binderMembers.Count; i++)
        {
            var member = binderMembers[i];
            var isNullable = member.IsNullable || member.BaseTypeName == "string" || member.BaseTypeName == "float[]";
            if (isNullable)
            {
                builder.AppendLine($"if (record.{member.MemberName} != null)");
                builder.AppendLine("{");
                builder.Indent();
                EmitWriteCall(builder, member);
                builder.Unindent();
                builder.AppendLine("}");
            }
            else
            {
                EmitWriteCall(builder, member);
            }
        }
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine();

        // Implement WriteRecordAsync (Synchronous buffering internally)
        builder.AppendLine($"public Task WriteRecordAsync(HtbRecordWriter<{descriptor.FullyQualifiedName}> writer, {descriptor.FullyQualifiedName} record)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("WriteRecord(writer, record);");
        builder.AppendLine("return Task.CompletedTask;");
        builder.Unindent();
        builder.AppendLine("}");

        builder.Unindent();
        builder.AppendLine("}"); // end of class

        context.AddSource($"HtbInlineBinder.{descriptor.SafeClassName}.g.cs", builder.ToString());
    }

    private static void EmitReadCall(SourceBuilder builder, MemberDescriptor member, bool isAsync)
    {
        var suffix = isAsync ? "Async()" : "()";
        var awaitPrefix = isAsync ? "await " : "";
        var baseType = member.BaseTypeName;
        var propertyName = member.MemberName;

#pragma warning disable IDE0010
        switch (baseType)
        {
            case "int":
            case "System.Int32":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadInt32{suffix};");
                break;
            case "long":
            case "System.Int64":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadInt64{suffix};");
                break;
            case "float":
            case "System.Single":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadFloat{suffix};");
                break;
            case "double":
            case "System.Double":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadDouble{suffix};");
                break;
            case "decimal":
            case "System.Decimal":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadDecimal{suffix};");
                break;
            case "bool":
            case "System.Boolean":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadBoolean{suffix};");
                break;
            case "System.DateTime":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadDateTime{suffix};");
                break;
            case "string":
            case "System.String":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadString{suffix};");
                break;
            case "System.Guid":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadGuid{suffix};");
                break;
            case "float[]":
            case "System.Single[]":
                builder.AppendLine($"instance.{propertyName} = {awaitPrefix}reader.ReadFloatArray{suffix};");
                break;
            default:
                break;
        }
#pragma warning restore IDE0010
    }

    private static void EmitWriteCall(SourceBuilder builder, MemberDescriptor member)
    {
        var baseType = member.BaseTypeName;
        var propertyName = member.MemberName;
        var accessValue = (member.IsNullable && baseType != "string" && baseType != "float[]") ? $"record.{propertyName}.Value" : $"record.{propertyName}";

#pragma warning disable IDE0010
        switch (baseType)
        {
            case "int":
            case "System.Int32":
                builder.AppendLine($"writer.WriteInt32({accessValue});");
                break;
            case "long":
            case "System.Int64":
                builder.AppendLine($"writer.WriteInt64({accessValue});");
                break;
            case "float":
            case "System.Single":
                builder.AppendLine($"writer.WriteFloat({accessValue});");
                break;
            case "double":
            case "System.Double":
                builder.AppendLine($"writer.WriteDouble({accessValue});");
                break;
            case "decimal":
            case "System.Decimal":
                builder.AppendLine($"writer.WriteDecimal({accessValue});");
                break;
            case "bool":
            case "System.Boolean":
                builder.AppendLine($"writer.WriteBoolean({accessValue});");
                break;
            case "System.DateTime":
                builder.AppendLine($"writer.WriteDateTime({accessValue});");
                break;
            case "string":
            case "System.String":
                builder.AppendLine($"writer.WriteString({accessValue});");
                break;
            case "System.Guid":
                builder.AppendLine($"writer.WriteGuid({accessValue});");
                break;
            case "float[]":
            case "System.Single[]":
                builder.AppendLine($"writer.WriteFloatArray({accessValue});");
                break;
            default:
                break;
        }
#pragma warning restore IDE0010
    }

    private static void EmitRegistration(SourceProductionContext context, IReadOnlyList<TypeDescriptor> descriptors)
    {
        var builder = new SourceBuilder(8192);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GENERATED_NAMESPACE};");
        builder.AppendLine();
        builder.AppendLine("file static class HtbRecordBinderGeneratedRegistration");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("[ModuleInitializer]");
        builder.AppendLine("internal static void Register()");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var descriptor in descriptors)
        {
            var binderClassName = $"global::{GENERATED_NAMESPACE}.HtbInlineBinder_{descriptor.SafeClassName}";
            builder.AppendLine($"{BINDER_FACTORY_TYPE}.RegisterBinder<{descriptor.FullyQualifiedName}>(schema => new {binderClassName}(schema));");
            builder.AppendLine($"{WRITER_FACTORY_TYPE}.RegisterWriter<{descriptor.FullyQualifiedName}>(() => new {binderClassName}());");

            builder.AppendLine($"global::HeroParser.Htbs.Records.HtbSchema.RegisterSchemaProvider<{descriptor.FullyQualifiedName}>(() => new global::HeroParser.Htbs.Records.HtbSchema(");
            builder.AppendLine("    new global::HeroParser.Htbs.Records.HtbColumn[]");
            builder.AppendLine("    {");
            for (int i = 0; i < descriptor.Members.Count; i++)
            {
                var member = descriptor.Members[i];
                var isNullable = member.IsNullable || member.BaseTypeName == "string" || member.BaseTypeName == "float[]";
                var isNullableStr = isNullable ? "true" : "false";
                var typeNameStr = GetHtbDataTypeName(member.BaseTypeName);
                var comma = i == descriptor.Members.Count - 1 ? "" : ",";
                builder.AppendLine($"        new global::HeroParser.Htbs.Records.HtbColumn(\"{member.HeaderName}\", global::HeroParser.Htbs.Records.HtbDataType.{typeNameStr}, {isNullableStr}){comma}");
            }
            builder.AppendLine("    }");
            builder.AppendLine("));");
        }

        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");

        context.AddSource("HtbRecordBinderFactory.Registration.g.cs", builder.ToString());
    }

    private static string GetHtbDataTypeName(string baseTypeName)
    {
        return baseTypeName switch
        {
            "int" or "System.Int32" => "Int32",
            "long" or "System.Int64" => "Int64",
            "float" or "System.Single" => "Float",
            "double" or "System.Double" => "Double",
            "decimal" or "System.Decimal" => "Decimal",
            "bool" or "System.Boolean" => "Boolean",
            "System.DateTime" => "DateTime",
            "string" or "System.String" => "String",
            "System.Guid" => "Guid",
            "float[]" or "System.Single[]" => "FloatArray",
            _ => "Unknown"
        };
    }

    private static TypeDescriptor? BuildDescriptor(INamedTypeSymbol type, CancellationToken ct)
    {
        var members = new List<MemberDescriptor>();
        var diagnostics = new List<Diagnostic>();

        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            ct.ThrowIfCancellationRequested();

            if (property.IsStatic)
                continue;

            var hasSetter = property.SetMethod is { DeclaredAccessibility: Accessibility.Public };
            var hasGetter = property.GetMethod is { DeclaredAccessibility: Accessibility.Public };

            if (!hasSetter && !hasGetter)
                continue;

            // [TabularMap]
            var mapAttribute = GetFirstMatchingAttribute(property, columnAttributeNames);
            string headerName = property.Name;
            int? attributeIndex = null;
            if (mapAttribute is not null)
            {
                foreach (var arg in mapAttribute.NamedArguments)
                {
                    if (arg.Key == "Name" && arg.Value.Value is string s && !string.IsNullOrWhiteSpace(s))
                    {
                        headerName = s;
                    }
                    else if (arg.Key == "Index" && arg.Value.Value is int i && i >= 0)
                    {
                        attributeIndex = i;
                    }
                }
            }

            var (baseTypeName, isNullable, isEnum) = GetBaseTypeInfo(property.Type);

#pragma warning disable IDE0010
            HtbDataType dataType = baseTypeName switch
            {
                "int" or "System.Int32" => HtbDataType.Int32,
                "long" or "System.Int64" => HtbDataType.Int64,
                "float" or "System.Single" => HtbDataType.Float,
                "double" or "System.Double" => HtbDataType.Double,
                "decimal" or "System.Decimal" => HtbDataType.Decimal,
                "bool" or "System.Boolean" => HtbDataType.Boolean,
                "System.DateTime" => HtbDataType.DateTime,
                "string" or "System.String" => HtbDataType.String,
                "System.Guid" => HtbDataType.Guid,
                "float[]" or "System.Single[]" => HtbDataType.FloatArray,
                _ => HtbDataType.Unknown
            };
#pragma warning restore IDE0010

            if (dataType == HtbDataType.Unknown)
            {
                // Skip unsupported properties
                continue;
            }

            var typeName = property.Type.ToDisplayString(FullyQualifiedFormatWithNullable);
            var typeofTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // [Validate] — NotNull, NotEmpty, MaxLength, MinLength, RangeMin, RangeMax, Pattern, PatternTimeoutMs
            bool validationNotNull = false;
            bool validationNotEmpty = false;
            int validationMaxLength = -1;
            int validationMinLength = -1;
            double validationRangeMin = double.NaN;
            double validationRangeMax = double.NaN;
            string? validationPattern = null;
            int validationPatternTimeoutMs = 1000;
            var validateAttribute = GetFirstMatchingAttribute(property, GeneratorHelpers.ValidateAttributeNames);
            if (validateAttribute is not null)
            {
                foreach (var arg in validateAttribute.NamedArguments)
                {
#pragma warning disable IDE0010
                    switch (arg.Key)
                    {
                        case "NotNull" when arg.Value.Value is bool r:
                            validationNotNull = r; break;
                        case "NotEmpty" when arg.Value.Value is bool ne:
                            validationNotEmpty = ne; break;
                        case "MaxLength" when arg.Value.Value is int ml && ml >= 0:
                            validationMaxLength = ml; break;
                        case "MinLength" when arg.Value.Value is int mnl && mnl >= 0:
                            validationMinLength = mnl; break;
                        case "RangeMin" when arg.Value.Value is double rmin && !double.IsNaN(rmin):
                            validationRangeMin = rmin; break;
                        case "RangeMax" when arg.Value.Value is double rmax && !double.IsNaN(rmax):
                            validationRangeMax = rmax; break;
                        case "Pattern" when arg.Value.Value is string p && !string.IsNullOrWhiteSpace(p):
                            validationPattern = p; break;
                        case "PatternTimeoutMs" when arg.Value.Value is int pt && pt > 0:
                            validationPatternTimeoutMs = pt; break;
                    }
#pragma warning restore IDE0010
                }
            }

            members.Add(new MemberDescriptor(
                property.Name,
                headerName,
                attributeIndex,
                typeName,
                typeofTypeName,
                baseTypeName,
                isNullable,
                validationNotNull,
                validationNotEmpty,
                validationMaxLength,
                validationMinLength,
                validationRangeMin,
                validationRangeMax,
                validationPattern,
                validationPatternTimeoutMs));
        }

        if (members.Count == 0 && diagnostics.Count == 0)
            return null;

        // Sort members in the exact same sorted order as HtbSchema.FromType<T>() (explicit Index ascending first, then alphabetical fallback)
        var sortedMembers = members
            .OrderBy(m => m.AttributeIndex.HasValue && m.AttributeIndex.Value >= 0 ? m.AttributeIndex.Value : int.MaxValue)
            .ThenBy(m => m.MemberName, StringComparer.Ordinal)
            .ToList();

        var fqName = type.ToDisplayString(FullyQualifiedFormatWithNullable);
        var safeClassName = CreateSafeClassName(type);
        return new TypeDescriptor(fqName, safeClassName, sortedMembers, diagnostics);
    }

    private static (string baseTypeName, bool isNullable, bool isEnum) GetBaseTypeInfo(ITypeSymbol type)
    {
        var underlying = type is INamedTypeSymbol named && named.IsGenericType && named.Name == "Nullable"
            ? named.TypeArguments[0]
            : type;

        var baseTypeName = underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "");

        if (baseTypeName == "System.String") baseTypeName = "string";
        else if (baseTypeName == "System.Single[]") baseTypeName = "float[]";

        bool isNullable = type is INamedTypeSymbol n && n.IsGenericType && n.Name == "Nullable";
        bool isEnum = underlying.TypeKind == TypeKind.Enum;

        return (baseTypeName, isNullable, isEnum);
    }

    private static void EmitHtbValidationChecks(SourceBuilder builder, MemberDescriptor member)
    {
        // 1. NotNull validation (already handled for null reads in BindField/BindFieldAsync before calling this helper)

        // 2. NotEmpty validation
        if (member.ValidationNotEmpty)
        {
            builder.AppendLine($"if (instance.{member.MemberName} is string s && string.IsNullOrWhiteSpace(s))");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.DeserializationError, \"Property '{member.MemberName}' violated validation constraint: value cannot be empty.\");");
            builder.Unindent();
            builder.AppendLine("}");
        }

        // 3. MinLength validation
        if (member.ValidationMinLength > 0)
        {
            builder.AppendLine($"if (instance.{member.MemberName} is string sMin && sMin.Length < {member.ValidationMinLength})");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.DeserializationError, \"Property '{member.MemberName}' violated validation constraint: length must be at least {member.ValidationMinLength}.\");");
            builder.Unindent();
            builder.AppendLine("}");
        }

        // 4. MaxLength validation
        if (member.ValidationMaxLength > 0)
        {
            builder.AppendLine($"if (instance.{member.MemberName} is string sMax && sMax.Length > {member.ValidationMaxLength})");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.DeserializationError, \"Property '{member.MemberName}' violated validation constraint: length cannot exceed {member.ValidationMaxLength}.\");");
            builder.Unindent();
            builder.AppendLine("}");
        }

        // 5 & 6. Range validation
        if (!double.IsNaN(member.ValidationRangeMin) || !double.IsNaN(member.ValidationRangeMax))
        {
            var valueExpr = $"instance.{member.MemberName}";
            builder.AppendLine($"double numericVal = Convert.ToDouble({valueExpr});");
            if (!double.IsNaN(member.ValidationRangeMin))
            {
                builder.AppendLine($"if (numericVal < {FormatRangeLiteral(member.ValidationRangeMin, "double")})");
                builder.AppendLine("{");
                builder.Indent();
                builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.DeserializationError, $\"Property '{member.MemberName}' violated validation constraint: value {{numericVal}} must be at least {member.ValidationRangeMin}.\");");
                builder.Unindent();
                builder.AppendLine("}");
            }
            if (!double.IsNaN(member.ValidationRangeMax))
            {
                builder.AppendLine($"if (numericVal > {FormatRangeLiteral(member.ValidationRangeMax, "double")})");
                builder.AppendLine("{");
                builder.Indent();
                builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.DeserializationError, $\"Property '{member.MemberName}' violated validation constraint: value {{numericVal}} cannot exceed {member.ValidationRangeMax}.\");");
                builder.Unindent();
                builder.AppendLine("}");
            }
        }

        // 7. Pattern validation
        if (member.ValidationPattern != null)
        {
            builder.AppendLine($"if (instance.{member.MemberName} is string sPat && !_pattern_{member.MemberName}.IsMatch(sPat))");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"throw new global::HeroParser.Htbs.HtbException(global::HeroParser.Htbs.HtbErrorCode.DeserializationError, \"Property '{member.MemberName}' violated validation constraint: value must match pattern '{EscapeString(member.ValidationPattern)}'.\");");
            builder.Unindent();
            builder.AppendLine("}");
        }
    }

    private static string FormatRangeLiteral(double value, string baseType)
    {
        return baseType switch
        {
            "decimal" or "System.Decimal" => $"{value}m",
            "float" or "System.Single" => $"{value}f",
            "double" or "System.Double" => $"{value}d",
            "long" or "System.Int64" => $"{(long)value}L",
            "ulong" or "System.UInt64" => $"{(ulong)value}UL",
            "int" or "System.Int32" => $"{(int)value}",
            "uint" or "System.UInt32" => $"{(uint)value}U",
            "short" or "System.Int16" => $"(short){(short)value}",
            "ushort" or "System.UInt16" => $"(ushort){(ushort)value}",
            "byte" or "System.Byte" => $"(byte){(byte)value}",
            "sbyte" or "System.SByte" => $"(sbyte){(sbyte)value}",
            _ => $"{value}"
        };
    }

    private sealed record TypeDescriptor(
        string FullyQualifiedName,
        string SafeClassName,
        IReadOnlyList<MemberDescriptor> Members,
        IReadOnlyList<Diagnostic> Diagnostics);

    private sealed record MemberDescriptor(
        string MemberName,
        string HeaderName,
        int? AttributeIndex,
        string TypeName,
        string TypeOfTypeName,
        string BaseTypeName,
        bool IsNullable,
        bool ValidationNotNull,
        bool ValidationNotEmpty,
        int ValidationMaxLength,
        int ValidationMinLength,
        double ValidationRangeMin,
        double ValidationRangeMax,
        string? ValidationPattern,
        int ValidationPatternTimeoutMs);
}
