using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using static HeroParser.Generators.GeneratorHelpers;

namespace HeroParser.Generators;

/// <summary>
/// Source generator for JSONL record binders.
/// Generates inline binder classes for maximum performance, Native AOT-safe parsing.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class JsonlRecordBinderGenerator : IIncrementalGenerator
{
    private const string GENERATED_NAMESPACE = "HeroParser.JsonLines.Reading.Binding";
    private const string BINDER_FACTORY_TYPE = "global::HeroParser.JsonLines.Reading.Binders.JsonlRecordBinderFactory";
    private const string BINDER_INTERFACE_TYPE = "global::HeroParser.JsonLines.Reading.Binders.IJsonlSourceBinder<";

    private static readonly string[] generateAttributeNames =
    [
        "HeroParser.GenerateBinderAttribute"
    ];

    private static readonly string[] columnAttributeNames =
    [
        "HeroParser.TabularMapAttribute"
    ];

    private static readonly string[] jsonPropertyAttributeNames =
    [
        "System.Text.Json.Serialization.JsonPropertyNameAttribute"
    ];

#pragma warning disable RS2008 // Enable analyzer release tracking - not needed for internal generator
    private static readonly DiagnosticDescriptor unsupportedPropertyTypeDiagnostic = new(
        "HERO101",
        "Unsupported property type for JSONL",
        "Property '{0}' of type '{1}' is not supported by the JSONL record binder generator. Supported types include primitives, DateTime, DateTimeOffset, DateOnly, TimeOnly, Guid, enums, and string.",
        "HeroParser.Generators",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);
#pragma warning restore RS2008

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Use ForAttributeWithMetadataName for better caching
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                generateAttributeNames[0],
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, ct) => TransformToDescriptor(ctx, ct))
            .Where(static x => x is not null);

        // Generate per-type typed binder files for better incrementality
        context.RegisterSourceOutput(provider, static (spc, descriptor) => EmitTypedBinder(spc, descriptor!));

        // Generate registration file
        context.RegisterSourceOutput(provider.Collect(), static (spc, descriptors) =>
        {
            var all = descriptors.Where(x => x is not null).ToList();
            if (all.Count > 0)
                EmitRegistration(spc, all!);
        });
    }

    private static TypeDescriptor? TransformToDescriptor(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract || !IsTypeAccessible(symbol))
            return null;

        return BuildDescriptor(symbol, ct);
    }

    private static void EmitTypedBinder(SourceProductionContext context, TypeDescriptor descriptor)
    {
        // Report diagnostics
        foreach (var diag in descriptor.Diagnostics)
        {
            context.ReportDiagnostic(diag);
        }

        var binderMembers = GetMembersWithSetters(descriptor.Members);
        if (binderMembers.Count == 0)
            return;

        var builder = new SourceBuilder(16384);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using HeroParser.JsonLines.Reading.Binders;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GENERATED_NAMESPACE};");
        builder.AppendLine();

        var binderClassName = $"JsonlInlineByteSourceBinder_{descriptor.SafeClassName}";
        builder.AppendLine($"internal sealed class {binderClassName} : {BINDER_INTERFACE_TYPE}byte, {descriptor.FullyQualifiedName}>");
        builder.AppendLine("{");
        builder.Indent();

        // Emit static property names keys (ReadOnlySpan<byte> properties)
        for (int i = 0; i < binderMembers.Count; i++)
        {
            var member = binderMembers[i];
            var candidates = GetKeyCandidates(member);
            for (int k = 0; k < candidates.Count; k++)
            {
                var candidate = EscapeString(candidates[k]);
                builder.AppendLine($"private static System.ReadOnlySpan<byte> Key_{member.MemberName}_{k} => \"{candidate}\"u8;");
            }
        }
        builder.AppendLine();

        builder.AppendLine($"internal static {BINDER_INTERFACE_TYPE}byte, {descriptor.FullyQualifiedName}> Instance {{ get; }} = new {binderClassName}();");
        builder.AppendLine();

        builder.AppendLine($"public {descriptor.FullyQualifiedName} Bind(ReadOnlySpan<byte> line)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var reader = new Utf8JsonReader(line);");
        builder.AppendLine("if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)");
        builder.AppendLine("    throw new JsonException(\"Expected start of JSON object.\");");
        builder.AppendLine();
        builder.AppendLine($"var record = new {descriptor.FullyQualifiedName}();");
        builder.AppendLine();
        builder.AppendLine("while (reader.Read())");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("if (reader.TokenType == JsonTokenType.EndObject)");
        builder.AppendLine("    return record;");
        builder.AppendLine();
        builder.AppendLine("if (reader.TokenType == JsonTokenType.PropertyName)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("var nameSpan = reader.ValueSpan;");
        builder.AppendLine("if (!reader.Read())");
        builder.AppendLine("    throw new JsonException(\"Expected property value.\");");
        builder.AppendLine();

        // Generate matching checks
        for (int i = 0; i < binderMembers.Count; i++)
        {
            var member = binderMembers[i];
            var candidates = GetKeyCandidates(member);
            var conditionParts = new List<string>();
            for (int k = 0; k < candidates.Count; k++)
            {
                conditionParts.Add($"nameSpan.SequenceEqual(Key_{member.MemberName}_{k})");
            }

            var condition = string.Join(" || ", conditionParts);
            builder.AppendLine($"{(i == 0 ? "if" : "else if")} ({condition})");
            builder.AppendLine("{");
            builder.Indent();
            EmitPropertyParsing(builder, member);
            builder.Unindent();
            builder.AppendLine("}");
        }

        builder.AppendLine("else");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("reader.Skip();");
        builder.Unindent();
        builder.AppendLine("}");

        builder.Unindent();
        builder.AppendLine("}"); // end of PropertyName check
        builder.Unindent();
        builder.AppendLine("}"); // end of loop
        builder.AppendLine();
        builder.AppendLine("throw new JsonException(\"JSON object was truncated or malformed.\");");
        builder.Unindent();
        builder.AppendLine("}"); // end of Bind method

        builder.Unindent();
        builder.AppendLine("}"); // end of byte class

        // Emit Char Source Binder implementing IJsonlSourceBinder<char, T>
        var charBinderClassName = $"JsonlInlineCharSourceBinder_{descriptor.SafeClassName}";
        builder.AppendLine();
        builder.AppendLine($"internal sealed class {charBinderClassName} : {BINDER_INTERFACE_TYPE}char, {descriptor.FullyQualifiedName}>");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine($"internal static {BINDER_INTERFACE_TYPE}char, {descriptor.FullyQualifiedName}> Instance {{ get; }} = new {charBinderClassName}();");
        builder.AppendLine();
        builder.AppendLine($"public {descriptor.FullyQualifiedName} Bind(ReadOnlySpan<char> line)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("if (line.IsEmpty)");
        builder.AppendLine($"    return {binderClassName}.Instance.Bind(ReadOnlySpan<byte>.Empty);");
        builder.AppendLine();
        builder.AppendLine("int maxByteCount = global::System.Text.Encoding.UTF8.GetMaxByteCount(line.Length);");
        builder.AppendLine("byte[]? rented = null;");
        builder.AppendLine("Span<byte> buffer = maxByteCount <= 512");
        builder.AppendLine("    ? stackalloc byte[maxByteCount]");
        builder.AppendLine("    : (rented = global::System.Buffers.ArrayPool<byte>.Shared.Rent(maxByteCount));");
        builder.AppendLine();
        builder.AppendLine("try");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("int bytesWritten = global::System.Text.Encoding.UTF8.GetBytes(line, buffer);");
        builder.AppendLine($"return {binderClassName}.Instance.Bind(buffer[..bytesWritten]);");
        builder.Unindent();
        builder.AppendLine("}");
        builder.AppendLine("finally");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("if (rented is not null)");
        builder.AppendLine("    global::System.Buffers.ArrayPool<byte>.Shared.Return(rented);");
        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}"); // end of Bind
        builder.Unindent();
        builder.AppendLine("}"); // end of char class

        context.AddSource($"JsonlInlineSourceBinder.{descriptor.SafeClassName}.g.cs", builder.ToString());
    }

    private static List<string> GetKeyCandidates(MemberDescriptor member)
    {
        var list = new List<string>();
        if (member.CustomJsonName is not null)
        {
            list.Add(member.CustomJsonName);
        }
        else
        {
            list.Add(member.MemberName);
            list.Add(JsonCamelCase(member.MemberName));
            list.Add(member.MemberName.ToLowerInvariant());
            if (member.HeaderName != member.MemberName && member.HeaderName is not null)
            {
                list.Add(member.HeaderName);
                list.Add(JsonCamelCase(member.HeaderName));
                list.Add(member.HeaderName.ToLowerInvariant());
            }
        }
        return [.. list.Distinct()];
    }

    private static string JsonCamelCase(string s)
    {
        if (string.IsNullOrEmpty(s) || !char.IsUpper(s[0]))
            return s;

        char[] chars = s.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
        {
            if (i == 1 && !char.IsUpper(chars[i]))
                break;

            bool hasNext = (i + 1 < chars.Length);
            if (i > 0 && hasNext && !char.IsUpper(chars[i + 1]))
                break;

            chars[i] = char.ToLowerInvariant(chars[i]);
        }
        return new string(chars);
    }

    private static void EmitPropertyParsing(SourceBuilder builder, MemberDescriptor member)
    {
        var propertyName = member.MemberName;
        var baseType = member.BaseTypeName;

        if (member.IsNullable)
        {
            builder.AppendLine("if (reader.TokenType == JsonTokenType.Null)");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"record.{propertyName} = null;");
            builder.Unindent();
            builder.AppendLine("}");
            builder.AppendLine("else");
            builder.AppendLine("{");
            builder.Indent();
        }

        switch (baseType)
        {
            case "string":
            case "System.String":
                builder.AppendLine($"record.{propertyName} = reader.GetString()!;");
                break;

            case "int":
            case "System.Int32":
                builder.AppendLine($"record.{propertyName} = reader.GetInt32();");
                break;

            case "long":
            case "System.Int64":
                builder.AppendLine($"record.{propertyName} = reader.GetInt64();");
                break;

            case "short":
            case "System.Int16":
                builder.AppendLine($"record.{propertyName} = reader.GetInt16();");
                break;

            case "byte":
            case "System.Byte":
                builder.AppendLine($"record.{propertyName} = reader.GetByte();");
                break;

            case "sbyte":
            case "System.SByte":
                builder.AppendLine($"record.{propertyName} = reader.GetSByte();");
                break;

            case "uint":
            case "System.UInt32":
                builder.AppendLine($"record.{propertyName} = reader.GetUInt32();");
                break;

            case "ulong":
            case "System.UInt64":
                builder.AppendLine($"record.{propertyName} = reader.GetUInt64();");
                break;

            case "ushort":
            case "System.UInt16":
                builder.AppendLine($"record.{propertyName} = reader.GetUInt16();");
                break;

            case "double":
            case "System.Double":
                builder.AppendLine($"record.{propertyName} = reader.GetDouble();");
                break;

            case "float":
            case "System.Single":
                builder.AppendLine($"record.{propertyName} = reader.GetSingle();");
                break;

            case "decimal":
            case "System.Decimal":
                builder.AppendLine($"record.{propertyName} = reader.GetDecimal();");
                break;

            case "bool":
            case "System.Boolean":
                builder.AppendLine($"record.{propertyName} = reader.GetBoolean();");
                break;

            case "System.DateTime":
                builder.AppendLine($"record.{propertyName} = reader.GetDateTime();");
                break;

            case "System.DateTimeOffset":
                builder.AppendLine($"record.{propertyName} = reader.GetDateTimeOffset();");
                break;

            case "System.Guid":
                builder.AppendLine($"record.{propertyName} = reader.GetGuid();");
                break;

            case "System.DateOnly":
                builder.AppendLine("{");
                builder.Indent();
                builder.AppendLine("string? s = reader.GetString();");
                builder.AppendLine($"record.{propertyName} = s is not null ? DateOnly.Parse(s) : default;");
                builder.Unindent();
                builder.AppendLine("}");
                break;

            case "System.TimeOnly":
                builder.AppendLine("{");
                builder.Indent();
                builder.AppendLine("string? s = reader.GetString();");
                builder.AppendLine($"record.{propertyName} = s is not null ? TimeOnly.Parse(s) : default;");
                builder.Unindent();
                builder.AppendLine("}");
                break;

            default:
                if (member.IsEnum)
                {
                    builder.AppendLine("if (reader.TokenType == JsonTokenType.Number)");
                    builder.AppendLine($"    record.{propertyName} = ({member.TypeOfTypeName})reader.GetInt32();");
                    builder.AppendLine("else if (reader.TokenType == JsonTokenType.String)");
                    builder.AppendLine("{");
                    builder.Indent();
                    builder.AppendLine("string s = reader.GetString()!;");
                    builder.AppendLine($"if (Enum.TryParse<{member.TypeOfTypeName}>(s, ignoreCase: true, out var enumVal))");
                    builder.AppendLine($"    record.{propertyName} = enumVal;");
                    builder.AppendLine("else");
                    builder.AppendLine($"    throw new JsonException($\"Failed to parse value '{{s}}' as enum {member.TypeOfTypeName}.\");");
                    builder.Unindent();
                    builder.AppendLine("}");
                }
                else
                {
                    builder.AppendLine($"record.{propertyName} = reader.GetString()!;");
                }
                break;
        }

        if (member.IsNullable)
        {
            builder.Unindent();
            builder.AppendLine("}");
        }
    }

    private static void EmitRegistration(SourceProductionContext context, IReadOnlyList<TypeDescriptor> descriptors)
    {
        var builder = new SourceBuilder(8192);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine();
        builder.AppendLine($"namespace {GENERATED_NAMESPACE};");
        builder.AppendLine();
        builder.AppendLine("file static class JsonlRecordBinderGeneratedRegistration");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("[ModuleInitializer]");
        builder.AppendLine("internal static void Register()");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var descriptor in descriptors)
        {
            var binderMembers = GetMembersWithSetters(descriptor.Members);
            if (binderMembers.Count > 0)
            {
                var byteBinderClassName = $"global::{GENERATED_NAMESPACE}.JsonlInlineByteSourceBinder_{descriptor.SafeClassName}";
                builder.AppendLine($"{BINDER_FACTORY_TYPE}.RegisterByteBinder<{descriptor.FullyQualifiedName}>({byteBinderClassName}.Instance);");

                var charBinderClassName = $"global::{GENERATED_NAMESPACE}.JsonlInlineCharSourceBinder_{descriptor.SafeClassName}";
                builder.AppendLine($"{BINDER_FACTORY_TYPE}.RegisterCharBinder<{descriptor.FullyQualifiedName}>({charBinderClassName}.Instance);");
            }
        }

        builder.Unindent();
        builder.AppendLine("}");
        builder.Unindent();
        builder.AppendLine("}");

        context.AddSource("JsonlRecordBinderFactory.Registration.g.cs", builder.ToString());
    }

    private static TypeDescriptor? BuildDescriptor(INamedTypeSymbol type, CancellationToken ct)
    {
        var members = new List<MemberDescriptor>();
        var diagnostics = new List<Diagnostic>();

        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            ct.ThrowIfCancellationRequested();

            if (property.IsStatic)
                continue;

            var hasSetter = property.SetMethod is { DeclaredAccessibility: Accessibility.Public };
            var hasGetter = property.GetMethod is { DeclaredAccessibility: Accessibility.Public };

            if (!hasSetter && !hasGetter)
                continue;

            // [TabularMap]
            var mapAttribute = GetFirstMatchingAttribute(property, columnAttributeNames);
            string? headerName = null;
            if (mapAttribute is not null)
            {
                foreach (var arg in mapAttribute.NamedArguments)
                {
                    if (arg.Key == "Name" && arg.Value.Value is string s && !string.IsNullOrWhiteSpace(s))
                    {
                        headerName = s;
                    }
                }
            }

            // [JsonPropertyName]
            var jsonPropertyAttribute = GetFirstMatchingAttribute(property, jsonPropertyAttributeNames);
            string? customJsonName = null;
            if (jsonPropertyAttribute is not null)
            {
                if (jsonPropertyAttribute.ConstructorArguments.Length > 0 && jsonPropertyAttribute.ConstructorArguments[0].Value is string s && !string.IsNullOrWhiteSpace(s))
                {
                    customJsonName = s;
                }
            }

            if (!IsSupportedType(property.Type))
            {
                diagnostics.Add(Diagnostic.Create(
                    unsupportedPropertyTypeDiagnostic,
                    property.Locations.FirstOrDefault() ?? Location.None,
                    property.Name,
                    property.Type.ToDisplayString()));
                continue;
            }

            var typeName = property.Type.ToDisplayString(FullyQualifiedFormatWithNullable);
            var typeofTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var (baseTypeName, isNullable, isEnum) = GetBaseTypeInfo(property.Type);

            members.Add(new MemberDescriptor(
                property.Name,
                headerName,
                typeName,
                typeofTypeName,
                baseTypeName,
                isNullable,
                isEnum,
                customJsonName,
                hasSetter));
        }

        if (members.Count == 0 && diagnostics.Count == 0)
            return null;

        var fqName = type.ToDisplayString(FullyQualifiedFormatWithNullable);
        var safeClassName = CreateSafeClassName(type);
        return new TypeDescriptor(fqName, safeClassName, members, diagnostics);
    }

    private static (string baseTypeName, bool isNullable, bool isEnum) GetBaseTypeInfo(ITypeSymbol type)
    {
        var underlying = type is INamedTypeSymbol named && named.IsGenericType && named.Name == "Nullable"
            ? named.TypeArguments[0]
            : type;

        var baseTypeName = underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "");

        bool isNullable = type is INamedTypeSymbol n && n.IsGenericType && n.Name == "Nullable";
        bool isEnum = underlying.TypeKind == TypeKind.Enum;

        return (baseTypeName, isNullable, isEnum);
    }

    private static List<MemberDescriptor> GetMembersWithSetters(IReadOnlyList<MemberDescriptor> members)
    {
        var list = new List<MemberDescriptor>();
        foreach (var m in members) if (m.HasSetter) list.Add(m);
        return list;
    }

    private sealed record TypeDescriptor(
        string FullyQualifiedName,
        string SafeClassName,
        IReadOnlyList<MemberDescriptor> Members,
        IReadOnlyList<Diagnostic> Diagnostics);

    private sealed record MemberDescriptor(
        string MemberName,
        string? HeaderName,
        string TypeName,
        string TypeOfTypeName,
        string BaseTypeName,
        bool IsNullable,
        bool IsEnum,
        string? CustomJsonName,
        bool HasSetter);
}
