using System.IO.Pipelines;

namespace HeroParser.SeparatedValues.Reading.Records;

public sealed partial class CsvRecordReaderBuilder<T>
{
    /// <summary>
    /// Reads records from a <see cref="PipeReader"/> asynchronously using generated byte binders.
    /// </summary>
    /// <remarks>
    /// Fluent maps are not supported on this path yet. When rows span multiple pipe segments,
    /// a temporary buffer is rented for binding that row only.
    /// </remarks>
    public IAsyncEnumerable<T> FromPipeReaderAsync(
        PipeReader reader,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(reader);
        ThrowIfMapConfigured();

        var (parserOptions, recordOptions) = GetOptions();
        return Csv.DeserializeRecordsAsync<T>(reader, recordOptions, parserOptions, cancellationToken);
    }
}
