using System.Runtime.Intrinsics.X86;
using System.Text;
using HeroParser.SeparatedValues.Core;
using HeroParser.SeparatedValues.Reading.Shared;
using Xunit;

namespace HeroParser.Tests.Internal;

/// <summary>
/// Forces specific SIMD levels via <see cref="HardwareCapabilities.Override"/> so each
/// branch in <c>CsvRowParser</c>'s SIMD dispatcher gets exercised on a single test run.
/// On AVX-512 hardware the default test path only hits the AVX-512 branch; without
/// these overrides the AVX2 + scalar fallbacks remain uncovered.
/// </summary>
[Trait("Category", "Unit")]
[Collection("AsyncWriterTests")] // mutates shared HardwareCapabilities state — run sequentially
public class CsvSimdLevelCoverageTests
{
    [GenerateBinder]
    public sealed class Row
    {
        [TabularMap(Name = "A")] public string A { get; set; } = "";
        [TabularMap(Name = "B")] public string B { get; set; } = "";
        [TabularMap(Name = "C")] public string C { get; set; } = "";
    }

    private static List<Row> Parse(string csv)
    {
        var reader = Csv.DeserializeRecords<Row>(csv, out _);
        var list = new List<Row>();
        foreach (var r in reader) list.Add(r);
        return list;
    }

    private static string Sample(int rows = 50)
    {
        var sb = new StringBuilder("A,B,C\n");
        for (int i = 0; i < rows; i++)
        {
            sb.AppendLine($"row{i}A,row{i}B,row{i}C");
        }
        return sb.ToString();
    }

    private static string SampleWithQuotes(int rows = 50)
    {
        var sb = new StringBuilder("A,B,C\n");
        for (int i = 0; i < rows; i++)
        {
            sb.AppendLine($"\"row{i}A\",\"row{i}B\",\"row{i}C\"");
        }
        return sb.ToString();
    }

    [Fact]
    public void Avx512Forced_Off_Avx2_On_Pclmul_On_Unquoted()
    {
        Assert.SkipUnless(Avx2.IsSupported, "Forces avx2 = true; requires real AVX2 hardware (skipping on ARM macOS).");
        using (HardwareCapabilities.Override(avx512BW: false, avx2: true, pclmulqdq: true))
        {
            var records = Parse(Sample(64));
            Assert.Equal(64, records.Count);
        }
    }

    [Fact]
    public void Avx512Forced_Off_Avx2_On_Pclmul_On_Quoted()
    {
        Assert.SkipUnless(Avx2.IsSupported, "Forces avx2 = true; requires real AVX2 hardware (skipping on ARM macOS).");
        using (HardwareCapabilities.Override(avx512BW: false, avx2: true, pclmulqdq: true))
        {
            var records = Parse(SampleWithQuotes(64));
            Assert.Equal(64, records.Count);
        }
    }

    [Fact]
    public void Avx512Forced_Off_Avx2_On_Pclmul_Off_Quoted()
    {
        Assert.SkipUnless(Avx2.IsSupported, "Forces avx2 = true; requires real AVX2 hardware (skipping on ARM macOS).");
        // Disabling PCLMULQDQ forces the non-CLMUL quote-handling branch in the AVX2 path.
        using (HardwareCapabilities.Override(avx512BW: false, avx2: true, pclmulqdq: false))
        {
            var records = Parse(SampleWithQuotes(64));
            Assert.Equal(64, records.Count);
        }
    }

    [Fact]
    public void Avx512Forced_Off_Avx2_Off_FallsBackToScalar()
    {
        // Disable both SIMD levels: parser must fall back to scalar.
        using (HardwareCapabilities.Override(avx512BW: false, avx2: false))
        {
            var records = Parse(Sample(20));
            Assert.Equal(20, records.Count);
        }
    }

    private static int CountRowsBytePath(string csv)
    {
        var reader = Csv.ReadFromByteSpan(Encoding.UTF8.GetBytes(csv));
        int count = 0;
        while (reader.MoveNext())
        {
            count++;
        }
        return count - 1;
    }

    private static int CountRowsCharPath(string csv)
    {
        // Csv.ReadFromCharSpan drives the UTF-16 SIMD code path directly,
        // bypassing the char-to-byte adapter that DeserializeRecords<T> uses
        // when a generated byte binder is available.
        var reader = Csv.ReadFromCharSpan(csv.AsSpan());
        int count = 0;
        while (reader.MoveNext())
        {
            count++;
        }
        // Subtract 1 for the header row.
        return count - 1;
    }

    [Fact]
    public void Avx512_UTF16_Path_Unquoted()
    {
        // Default capabilities: AVX-512 path runs on this CPU.
        Assert.Equal(64, CountRowsCharPath(Sample(64)));
    }

    [Fact]
    public void Avx512_UTF16_Path_Quoted_WithPclmul()
    {
        Assert.Equal(64, CountRowsCharPath(SampleWithQuotes(64)));
    }

    [Fact]
    public void Avx512_UTF16_Path_Quoted_WithoutPclmul()
    {
        using (HardwareCapabilities.Override(pclmulqdq: false))
        {
            Assert.Equal(64, CountRowsCharPath(SampleWithQuotes(64)));
        }
    }

    [Fact]
    public void Avx2_UTF16_Path_FallbackWhenAvx512Disabled_Unquoted()
    {
        using (HardwareCapabilities.Override(avx512BW: false))
        {
            Assert.Equal(64, CountRowsCharPath(Sample(64)));
        }
    }

    [Fact]
    public void Avx2_UTF16_Path_FallbackWhenAvx512Disabled_Quoted()
    {
        using (HardwareCapabilities.Override(avx512BW: false))
        {
            Assert.Equal(64, CountRowsCharPath(SampleWithQuotes(64)));
        }
    }

    [Fact]
    public void Avx2_UTF16_Path_QuotedWithoutPclmul()
    {
        using (HardwareCapabilities.Override(avx512BW: false, pclmulqdq: false))
        {
            Assert.Equal(64, CountRowsCharPath(SampleWithQuotes(64)));
        }
    }

    [Fact]
    public void Scalar_UTF16_Path_NoSimdAvailable()
    {
        using (HardwareCapabilities.Override(avx512BW: false, avx2: false))
        {
            Assert.Equal(20, CountRowsCharPath(Sample(20)));
        }
    }

    [Fact]
    public void Avx512_UTF8_Path_Unquoted()
    {
        Assert.Equal(64, CountRowsBytePath(Sample(64)));
    }

    [Fact]
    public void Avx512_UTF8_Path_Quoted_WithPclmul()
    {
        Assert.Equal(64, CountRowsBytePath(SampleWithQuotes(64)));
    }

    [Fact]
    public void Avx512_UTF8_Path_Quoted_WithoutPclmul()
    {
        using (HardwareCapabilities.Override(pclmulqdq: false))
        {
            Assert.Equal(64, CountRowsBytePath(SampleWithQuotes(64)));
        }
    }

    [Fact]
    public void Avx2_UTF8_Path_FallbackWhenAvx512Disabled_Unquoted()
    {
        using (HardwareCapabilities.Override(avx512BW: false))
        {
            Assert.Equal(64, CountRowsBytePath(Sample(64)));
        }
    }

    [Fact]
    public void Avx2_UTF8_Path_FallbackWhenAvx512Disabled_Quoted()
    {
        using (HardwareCapabilities.Override(avx512BW: false))
        {
            Assert.Equal(64, CountRowsBytePath(SampleWithQuotes(64)));
        }
    }

    [Fact]
    public void Avx2_UTF8_Path_QuotedWithoutPclmul()
    {
        using (HardwareCapabilities.Override(avx512BW: false, pclmulqdq: false))
        {
            Assert.Equal(64, CountRowsBytePath(SampleWithQuotes(64)));
        }
    }

    [Fact]
    public void Scalar_UTF8_Path_NoSimdAvailable()
    {
        using (HardwareCapabilities.Override(avx512BW: false, avx2: false))
        {
            Assert.Equal(20, CountRowsBytePath(Sample(20)));
        }
    }

    [Fact]
    public void OverrideScope_RestoresPreviousValuesOnDispose()
    {
        var beforeAvx2 = HardwareCapabilities.Avx2IsSupported;
        var beforeAvx512 = HardwareCapabilities.Avx512BWIsSupported;

        using (HardwareCapabilities.Override(avx2: false, avx512BW: false))
        {
            Assert.False(HardwareCapabilities.Avx2IsSupported);
            Assert.False(HardwareCapabilities.Avx512BWIsSupported);
        }

        Assert.Equal(beforeAvx2, HardwareCapabilities.Avx2IsSupported);
        Assert.Equal(beforeAvx512, HardwareCapabilities.Avx512BWIsSupported);
    }

    [Fact]
    public void NestedOverrides_RestoreCorrectly()
    {
        using (HardwareCapabilities.Override(avx2: false))
        {
            Assert.False(HardwareCapabilities.Avx2IsSupported);
            using (HardwareCapabilities.Override(avx512BW: false))
            {
                Assert.False(HardwareCapabilities.Avx512BWIsSupported);
                Assert.False(HardwareCapabilities.Avx2IsSupported); // outer override still in effect
            }
            Assert.False(HardwareCapabilities.Avx2IsSupported); // outer override still in effect after inner disposed
        }
    }

    [Fact]
    public void Override_AllNullArgs_ChangesNothing()
    {
        var beforeAvx2 = HardwareCapabilities.Avx2IsSupported;
        using (HardwareCapabilities.Override())
        {
            Assert.Equal(beforeAvx2, HardwareCapabilities.Avx2IsSupported);
        }
    }

    [Fact]
    public void Override_DoubleDispose_NoThrow()
    {
        var scope = HardwareCapabilities.Override(avx2: false);
        scope.Dispose();
        scope.Dispose(); // second dispose should be a no-op
    }

    [Fact]
    public void Hardware_GetHardwareInfo_ReturnsString()
    {
        var info = HeroParser.Hardware.GetHardwareInfo();
        Assert.NotNull(info);
        Assert.NotEmpty(info);
    }
}
